[package]
name = "bybe-db"
version = "1.0.0"
authors = ["RakuJa"]

# Compiler info
edition = "2021"
rust-version = "1.77.1"

description = "a Database to help develop tools for Pathfinder 2e. It's built for the BYBE webservice"
readme = "README.md"
homepage = "https://backbybe.fly.dev/"
repository = "https://github.com/RakuJa/BYBE-DB"
license = "MIT"
keywords = ["database", "pathfinder"]
publish = false

build="build/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lints.rust]
unsafe_code = "forbid"

[dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread", "rt"] }
anyhow = "1.0.83"
maplit = "1.0.2"

serde_json = "1.0.117"
serde = { version = "1.0.201", features = ["derive"] }

git2 = "0.18.3"

strum = {version= "0.26.2", features = ["derive"]}

sqlx = { version = "0.7.4", features = ["runtime-async-std", "sqlite"] }
dotenvy = "0.15.7"

[build-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread", "rt"] }
anyhow = "1.0.83"
sqlx = { version = "0.7.4", features = ["runtime-async-std", "sqlite"] }
dotenv = "0.15.0"
