[package]
name = "bybe-db"
version = "1.0.0"
authors = ["RakuJa"]

# Compiler info
edition = "2021"
rust-version = "1.76.0"

description = "a Database to help develop tools for Pathfinder 2e. It's built for the BYBE webservice"
readme = "README.md"
homepage = "https://backbybe.fly.dev/"
repository = "https://github.com/RakuJa/BYBE-DB"
license = "MIT"
keywords = ["database", "pathfinder"]
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lints.rust]
unsafe_code = "forbid"

[dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread", "rt"] }
anyhow = "1.0.80"
maplit = "1.0.2"

serde_json = "1.0.114"
serde = { version = "1.0.197", features = ["derive"] }

git2 = "0.18.2"

strum = {version= "0.26.1", features = ["derive"]}

sqlx = { version = "0.7.3", features = ["runtime-async-std", "sqlite"] }
