[package]
name = "bybe-db"
version = "1.1.0"
authors = ["RakuJa"]

# Compiler info
edition = "2021"
rust-version = "1.77.1"

description = "a Database to help develop tools for Pathfinder 2e. It's built for the BYBE webservice"
readme = "README.md"
homepage = "https://backbybe.fly.dev/"
repository = "https://github.com/RakuJa/BYBE-DB"
license = "MIT"
keywords = ["database", "pathfinder"]
publish = false

build="build/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lints.rust]
unsafe_code = "forbid"

[dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread", "rt"] }
anyhow = "1.0.93"
maplit = "1.0.2"

once_cell = "1.20.2"
regex = "1.11.1"
evalexpr = "11.3.1"
capitalize = "0.3.4"

serde_json = "1.0.132"
serde = { version = "1.0.214", features = ["derive"] }

git2 = "0.19.0"

strum = {version= "0.26.3", features = ["derive"]}

sqlx = { version = "0.8.2", features = ["runtime-async-std", "sqlite"] }
dotenvy = "0.15.7"

[build-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread", "rt"] }
anyhow = "1.0.93"
sqlx = { version = "0.8.2", features = ["runtime-async-std", "sqlite"] }
dotenv = "0.15.0"

[dev-dependencies]
rstest = "0.23.0"
