UPDATE CREATURE_TABLE set aon_id = 882, cr_type = 'Npc', family = 'Courtiers' WHERE UPPER(name) = UPPER('Noble');
UPDATE CREATURE_TABLE set aon_id = 883, cr_type = 'Npc', family = 'Courtiers' WHERE UPPER(name) = UPPER('Palace Guard');
UPDATE CREATURE_TABLE set aon_id = 884, cr_type = 'Npc', family = 'Courtiers' WHERE UPPER(name) = UPPER('Advisor');
UPDATE CREATURE_TABLE set aon_id = 885, cr_type = 'Npc', family = 'Courtiers' WHERE UPPER(name) = UPPER('Spy');
UPDATE CREATURE_TABLE set aon_id = 886, cr_type = 'Npc', family = 'Criminals' WHERE UPPER(name) = UPPER('Grave Robber');
UPDATE CREATURE_TABLE set aon_id = 887, cr_type = 'Npc', family = 'Criminals' WHERE UPPER(name) = UPPER('Bandit');
UPDATE CREATURE_TABLE set aon_id = 888, cr_type = 'Npc', family = 'Criminals' WHERE UPPER(name) = UPPER('Ruffian');
UPDATE CREATURE_TABLE set aon_id = 889, cr_type = 'Npc', family = 'Criminals' WHERE UPPER(name) = UPPER('Charlatan');
UPDATE CREATURE_TABLE set aon_id = 890, cr_type = 'Npc', family = 'Criminals' WHERE UPPER(name) = UPPER('Burglar');
UPDATE CREATURE_TABLE set aon_id = 891, cr_type = 'Npc', family = 'Criminals' WHERE UPPER(name) = UPPER('Fence');
UPDATE CREATURE_TABLE set aon_id = 892, cr_type = 'Npc', family = 'Criminals' WHERE UPPER(name) = UPPER('Assassin');
UPDATE CREATURE_TABLE set aon_id = 894, cr_type = 'Npc', family = 'Devotees' WHERE UPPER(name) = UPPER('Prophet');
UPDATE CREATURE_TABLE set aon_id = 897, cr_type = 'Npc', family = 'Downtrodden' WHERE UPPER(name) = UPPER('Beggar');
UPDATE CREATURE_TABLE set aon_id = 898, cr_type = 'Npc', family = 'Downtrodden' WHERE UPPER(name) = UPPER('Commoner');
UPDATE CREATURE_TABLE set aon_id = 899, cr_type = 'Npc', family = 'Downtrodden' WHERE UPPER(name) = UPPER('Urchin');
UPDATE CREATURE_TABLE set aon_id = 900, cr_type = 'Npc', family = 'Downtrodden' WHERE UPPER(name) = UPPER('Prisoner');
UPDATE CREATURE_TABLE set aon_id = 901, cr_type = 'Npc', family = 'Explorers' WHERE UPPER(name) = UPPER('Torchbearer');
UPDATE CREATURE_TABLE set aon_id = 902, cr_type = 'Npc', family = 'Explorers' WHERE UPPER(name) = UPPER('Chronicler');
UPDATE CREATURE_TABLE set aon_id = 903, cr_type = 'Npc', family = 'Explorers' WHERE UPPER(name) = UPPER('Guide');
UPDATE CREATURE_TABLE set aon_id = 904, cr_type = 'Npc', family = 'Explorers' WHERE UPPER(name) = UPPER('Tomb Raider');
UPDATE CREATURE_TABLE set aon_id = 905, cr_type = 'Npc', family = 'Foresters' WHERE UPPER(name) = UPPER('Poacher');
UPDATE CREATURE_TABLE set aon_id = 906, cr_type = 'Npc', family = 'Foresters' WHERE UPPER(name) = UPPER('Tracker');
UPDATE CREATURE_TABLE set aon_id = 907, cr_type = 'Npc', family = 'Foresters' WHERE UPPER(name) = UPPER('Hunter');
UPDATE CREATURE_TABLE set aon_id = 908, cr_type = 'Npc', family = 'Healers' WHERE UPPER(name) = UPPER('Apothecary');
UPDATE CREATURE_TABLE set aon_id = 909, cr_type = 'Npc', family = 'Healers' WHERE UPPER(name) = UPPER('Physician');
UPDATE CREATURE_TABLE set aon_id = 910, cr_type = 'Npc', family = 'Healers' WHERE UPPER(name) = UPPER('Surgeon');
UPDATE CREATURE_TABLE set aon_id = 911, cr_type = 'Npc', family = 'Healers' WHERE UPPER(name) = UPPER('Plague Doctor');
UPDATE CREATURE_TABLE set aon_id = 912, cr_type = 'Npc', family = 'Laborers' WHERE UPPER(name) = UPPER('Servant');
UPDATE CREATURE_TABLE set aon_id = 913, cr_type = 'Npc', family = 'Laborers' WHERE UPPER(name) = UPPER('Dockhand');
UPDATE CREATURE_TABLE set aon_id = 914, cr_type = 'Npc', family = 'Laborers' WHERE UPPER(name) = UPPER('Farmer');
UPDATE CREATURE_TABLE set aon_id = 915, cr_type = 'Npc', family = 'Laborers' WHERE UPPER(name) = UPPER('Miner');
UPDATE CREATURE_TABLE set aon_id = 916, cr_type = 'Npc', family = 'Laborers' WHERE UPPER(name) = UPPER('Gravedigger');
UPDATE CREATURE_TABLE set aon_id = 917, cr_type = 'Npc', family = 'Magistrates' WHERE UPPER(name) = UPPER('Judge');
UPDATE CREATURE_TABLE set aon_id = 918, cr_type = 'Npc', family = 'Magistrates' WHERE UPPER(name) = UPPER('Tax Collector');
UPDATE CREATURE_TABLE set aon_id = 919, cr_type = 'Npc', family = 'Magistrates' WHERE UPPER(name) = UPPER('Harbormaster');
UPDATE CREATURE_TABLE set aon_id = 920, cr_type = 'Npc', family = 'Magistrates' WHERE UPPER(name) = UPPER('Warden');
UPDATE CREATURE_TABLE set aon_id = 921, cr_type = 'Npc', family = 'Mercenaries' WHERE UPPER(name) = UPPER('Bodyguard');
UPDATE CREATURE_TABLE set aon_id = 922, cr_type = 'Npc', family = 'Mercenaries' WHERE UPPER(name) = UPPER('Mage for Hire');
UPDATE CREATURE_TABLE set aon_id = 923, cr_type = 'Npc', family = 'Mercenaries' WHERE UPPER(name) = UPPER('Bounty Hunter');
UPDATE CREATURE_TABLE set aon_id = 924, cr_type = 'Npc', family = 'Mercenaries' WHERE UPPER(name) = UPPER('Monster Hunter');
UPDATE CREATURE_TABLE set aon_id = 925, cr_type = 'Npc', family = 'Mystics' WHERE UPPER(name) = UPPER('Adept');
UPDATE CREATURE_TABLE set aon_id = 926, cr_type = 'Npc', family = 'Mystics' WHERE UPPER(name) = UPPER('Harrow Reader');
UPDATE CREATURE_TABLE set aon_id = 927, cr_type = 'Npc', family = 'Mystics' WHERE UPPER(name) = UPPER('Cultist');
UPDATE CREATURE_TABLE set aon_id = 928, cr_type = 'Npc', family = 'Mystics' WHERE UPPER(name) = UPPER('False Priest');
UPDATE CREATURE_TABLE set aon_id = 929, cr_type = 'Npc', family = 'Mystics' WHERE UPPER(name) = UPPER('Necromancer');
UPDATE CREATURE_TABLE set aon_id = 930, cr_type = 'Npc', family = 'Mystics' WHERE UPPER(name) = UPPER('Cult Leader');
UPDATE CREATURE_TABLE set aon_id = 931, cr_type = 'Npc', family = 'Mystics' WHERE UPPER(name) = UPPER('Demonologist');
UPDATE CREATURE_TABLE set aon_id = 932, cr_type = 'Npc', family = 'Officers' WHERE UPPER(name) = UPPER('Barrister');
UPDATE CREATURE_TABLE set aon_id = 933, cr_type = 'Npc', family = 'Officers' WHERE UPPER(name) = UPPER('Guard');
UPDATE CREATURE_TABLE set aon_id = 934, cr_type = 'Npc', family = 'Officers' WHERE UPPER(name) = UPPER('Archer Sentry');
UPDATE CREATURE_TABLE set aon_id = 935, cr_type = 'Npc', family = 'Officers' WHERE UPPER(name) = UPPER('Jailer');
UPDATE CREATURE_TABLE set aon_id = 936, cr_type = 'Npc', family = 'Officers' WHERE UPPER(name) = UPPER('Watch Officer');
UPDATE CREATURE_TABLE set aon_id = 937, cr_type = 'Npc', family = 'Officers' WHERE UPPER(name) = UPPER('Captain Of The Guard');
UPDATE CREATURE_TABLE set aon_id = 938, cr_type = 'Npc', family = 'Officers' WHERE UPPER(name) = UPPER('Executioner');
UPDATE CREATURE_TABLE set aon_id = 939, cr_type = 'Npc', family = 'Performers' WHERE UPPER(name) = UPPER('Dancer');
UPDATE CREATURE_TABLE set aon_id = 940, cr_type = 'Npc', family = 'Performers' WHERE UPPER(name) = UPPER('Acrobat');
UPDATE CREATURE_TABLE set aon_id = 941, cr_type = 'Npc', family = 'Performers' WHERE UPPER(name) = UPPER('Troubadour');
UPDATE CREATURE_TABLE set aon_id = 942, cr_type = 'Npc', family = 'Performers' WHERE UPPER(name) = UPPER('Beast Tamer');
UPDATE CREATURE_TABLE set aon_id = 943, cr_type = 'Npc', family = 'Publicans' WHERE UPPER(name) = UPPER('Server');
UPDATE CREATURE_TABLE set aon_id = 944, cr_type = 'Npc', family = 'Publicans' WHERE UPPER(name) = UPPER('Barkeep');
UPDATE CREATURE_TABLE set aon_id = 945, cr_type = 'Npc', family = 'Publicans' WHERE UPPER(name) = UPPER('Innkeeper');
UPDATE CREATURE_TABLE set aon_id = 946, cr_type = 'Npc', family = 'Publicans' WHERE UPPER(name) = UPPER('Drunkard');
UPDATE CREATURE_TABLE set aon_id = 947, cr_type = 'Npc', family = 'Scholars' WHERE UPPER(name) = UPPER('Librarian');
UPDATE CREATURE_TABLE set aon_id = 948, cr_type = 'Npc', family = 'Scholars' WHERE UPPER(name) = UPPER('Teacher');
UPDATE CREATURE_TABLE set aon_id = 949, cr_type = 'Npc', family = 'Scholars' WHERE UPPER(name) = UPPER('Astronomer');
UPDATE CREATURE_TABLE set aon_id = 950, cr_type = 'Npc', family = 'Scholars' WHERE UPPER(name) = UPPER('Sage');
UPDATE CREATURE_TABLE set aon_id = 951, cr_type = 'Npc', family = 'Seafarers' WHERE UPPER(name) = UPPER('Navigator');
UPDATE CREATURE_TABLE set aon_id = 952, cr_type = 'Npc', family = 'Seafarers' WHERE UPPER(name) = UPPER('Pirate');
UPDATE CREATURE_TABLE set aon_id = 953, cr_type = 'Npc', family = 'Seafarers' WHERE UPPER(name) = UPPER('Bosun');
UPDATE CREATURE_TABLE set aon_id = 954, cr_type = 'Npc', family = 'Seafarers' WHERE UPPER(name) = UPPER('Ship Captain');
UPDATE CREATURE_TABLE set aon_id = 955, cr_type = 'Npc', family = 'Tradespeople' WHERE UPPER(name) = UPPER('Apprentice');
UPDATE CREATURE_TABLE set aon_id = 956, cr_type = 'Npc', family = 'Tradespeople' WHERE UPPER(name) = UPPER('Merchant');
UPDATE CREATURE_TABLE set aon_id = 957, cr_type = 'Npc', family = 'Tradespeople' WHERE UPPER(name) = UPPER('Smith');
UPDATE CREATURE_TABLE set aon_id = 958, cr_type = 'Npc', family = 'Tradespeople' WHERE UPPER(name) = UPPER('Guildmaster');
UPDATE CREATURE_TABLE set aon_id = 959, cr_type = 'Npc', family = 'Villains' WHERE UPPER(name) = UPPER('Saboteur');
UPDATE CREATURE_TABLE set aon_id = 960, cr_type = 'Npc', family = 'Villains' WHERE UPPER(name) = UPPER('Mastermind');
UPDATE CREATURE_TABLE set aon_id = 961, cr_type = 'Npc', family = 'Villains' WHERE UPPER(name) = UPPER('Antipaladin');
UPDATE CREATURE_TABLE set aon_id = 962, cr_type = 'Npc', family = 'Villains' WHERE UPPER(name) = UPPER('Despot');
UPDATE CREATURE_TABLE set aon_id = 963, cr_type = 'Npc', family = 'Villains' WHERE UPPER(name) = UPPER('Reckless Scientist');
UPDATE CREATURE_TABLE set aon_id = 964, cr_type = 'Npc', family = 'Villains' WHERE UPPER(name) = UPPER('Gang Leader');
UPDATE CREATURE_TABLE set aon_id = 965, cr_type = 'Npc', family = 'Firebrands' WHERE UPPER(name) = UPPER('Charming Scoundrel');
UPDATE CREATURE_TABLE set aon_id = 966, cr_type = 'Npc', family = 'Firebrands' WHERE UPPER(name) = UPPER('Privateer Captain');
UPDATE CREATURE_TABLE set aon_id = 967, cr_type = 'Npc', family = 'Hellknights' WHERE UPPER(name) = UPPER('Hellknight Armiger');
UPDATE CREATURE_TABLE set aon_id = 968, cr_type = 'Npc', family = 'Hellknights' WHERE UPPER(name) = UPPER('Hellknight Paravicar');
UPDATE CREATURE_TABLE set aon_id = 969, cr_type = 'Npc', family = 'Knights of Lastwall' WHERE UPPER(name) = UPPER('Virtuous Defender');
UPDATE CREATURE_TABLE set aon_id = 970, cr_type = 'Npc', family = 'Knights of Lastwall' WHERE UPPER(name) = UPPER('Veteran Reclaimer');
UPDATE CREATURE_TABLE set aon_id = 971, cr_type = 'Npc', family = 'Magaambyan Adepts' WHERE UPPER(name) = UPPER('Rain-Scribe');
UPDATE CREATURE_TABLE set aon_id = 972, cr_type = 'Npc', family = 'Magaambyan Adepts' WHERE UPPER(name) = UPPER('Tempest-Sun Mage');
UPDATE CREATURE_TABLE set aon_id = 973, cr_type = 'Npc', family = 'Pathfinders' WHERE UPPER(name) = UPPER('Pathfinder Field Agent');
UPDATE CREATURE_TABLE set aon_id = 974, cr_type = 'Npc', family = 'Pathfinders' WHERE UPPER(name) = UPPER('Pathfinder Venture-Captain');
UPDATE CREATURE_TABLE set aon_id = 1161, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Edolpho Phinelli');
UPDATE CREATURE_TABLE set aon_id = 1446, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Ji-yook (Level 9)');
UPDATE CREATURE_TABLE set aon_id = 1447, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Takatorra (Level 9)');
UPDATE CREATURE_TABLE set aon_id = 1448, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Yabin the Just (Level 9)');
UPDATE CREATURE_TABLE set aon_id = 1449, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Weapon Master');
UPDATE CREATURE_TABLE set aon_id = 1450, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Agile Warrior');
UPDATE CREATURE_TABLE set aon_id = 1451, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Ki Adept');
UPDATE CREATURE_TABLE set aon_id = 1452, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Archery Specialist');
UPDATE CREATURE_TABLE set aon_id = 1453, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Mage of Many Styles');
UPDATE CREATURE_TABLE set aon_id = 1466, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Gomwai');
UPDATE CREATURE_TABLE set aon_id = 1468, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER("Hana's Hundreds");
UPDATE CREATURE_TABLE set aon_id = 1471, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Koto Zekora');
UPDATE CREATURE_TABLE set aon_id = 1472, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Butterfly Blade Warrior');
UPDATE CREATURE_TABLE set aon_id = 1478, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Nai Yan Fei');
UPDATE CREATURE_TABLE set aon_id = 1481, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Kas Xi Rai');
UPDATE CREATURE_TABLE set aon_id = 1482, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Master Xun');
UPDATE CREATURE_TABLE set aon_id = 1483, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Tino Tung (Level 13)');
UPDATE CREATURE_TABLE set aon_id = 1484, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Ji-yook (Level 13)');
UPDATE CREATURE_TABLE set aon_id = 1485, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Takatorra (Level 13)');
UPDATE CREATURE_TABLE set aon_id = 1486, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Yabin the Just (Level 13)');
UPDATE CREATURE_TABLE set aon_id = 1490, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Artus Rodrivan');
UPDATE CREATURE_TABLE set aon_id = 1491, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Lantondo');
UPDATE CREATURE_TABLE set aon_id = 1492, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Syu Tak-nwa (Level 16)');
UPDATE CREATURE_TABLE set aon_id = 1493, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Blue Viper (Level 16)');
UPDATE CREATURE_TABLE set aon_id = 1494, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Shino Hakusa (Level 16)');
UPDATE CREATURE_TABLE set aon_id = 1495, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Ran-to (Level 16)');
UPDATE CREATURE_TABLE set aon_id = 1496, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Mafika Ayuwari');
UPDATE CREATURE_TABLE set aon_id = 1497, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Akila Stormheel');
UPDATE CREATURE_TABLE set aon_id = 1498, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Hummingbird');
UPDATE CREATURE_TABLE set aon_id = 1500, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Surjit Hamelan');
UPDATE CREATURE_TABLE set aon_id = 1501, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Umbasi');
UPDATE CREATURE_TABLE set aon_id = 1502, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Amihan');
UPDATE CREATURE_TABLE set aon_id = 1503, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Maalya');
UPDATE CREATURE_TABLE set aon_id = 1504, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Halspin the Stung');
UPDATE CREATURE_TABLE set aon_id = 1505, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Joon-seo');
UPDATE CREATURE_TABLE set aon_id = 1506, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Urnak Lostwind');
UPDATE CREATURE_TABLE set aon_id = 1507, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Huldrin Skolsdottir');
UPDATE CREATURE_TABLE set aon_id = 1508, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Juspix Rammel');
UPDATE CREATURE_TABLE set aon_id = 1509, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Troff Frostknuckles');
UPDATE CREATURE_TABLE set aon_id = 1512, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Razu');
UPDATE CREATURE_TABLE set aon_id = 1513, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Rai Sho Postulant');
UPDATE CREATURE_TABLE set aon_id = 1514, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Rai Sho Disciple');
UPDATE CREATURE_TABLE set aon_id = 1515, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Abbot Tsujon');
UPDATE CREATURE_TABLE set aon_id = 1516, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Jin-hae');
UPDATE CREATURE_TABLE set aon_id = 1521, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Tino (Oni Form)');
UPDATE CREATURE_TABLE set aon_id = 1522, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Ji-yook (Gumiho Form)');
UPDATE CREATURE_TABLE set aon_id = 1523, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Takatorra (Daitengu Form)');
UPDATE CREATURE_TABLE set aon_id = 1525, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Syu Tak-nwa (Level 20)');
UPDATE CREATURE_TABLE set aon_id = 1526, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Shino Hakusa (Level 20)');
UPDATE CREATURE_TABLE set aon_id = 1527, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Ran-to (Level 20)');
UPDATE CREATURE_TABLE set aon_id = 1528, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Blue Viper (Level 20)');
UPDATE CREATURE_TABLE set aon_id = 1529, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Spinel Leviathan Syndara');
UPDATE CREATURE_TABLE set aon_id = 1530, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Syndara the Sculptor');
UPDATE CREATURE_TABLE set aon_id = 1531, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Alak Stagram');
UPDATE CREATURE_TABLE set aon_id = 1532, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Calmont');
UPDATE CREATURE_TABLE set aon_id = 1535, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Bloody Blade Mercenary');
UPDATE CREATURE_TABLE set aon_id = 1536, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Dmiri Yoltosha');
UPDATE CREATURE_TABLE set aon_id = 1538, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Voz Lirayne');
UPDATE CREATURE_TABLE set aon_id = 1539, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Warbal Bumblebrasher');
UPDATE CREATURE_TABLE set aon_id = 1541, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Jahsi');
UPDATE CREATURE_TABLE set aon_id = 1542, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Racharak');
UPDATE CREATURE_TABLE set aon_id = 1543, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Gerhard Pendergrast');
UPDATE CREATURE_TABLE set aon_id = 1544, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Hezle');
UPDATE CREATURE_TABLE set aon_id = 1547, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Nketiah');
UPDATE CREATURE_TABLE set aon_id = 1548, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Heuberk Thropp');
UPDATE CREATURE_TABLE set aon_id = 1549, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Scarlet Triad Sneak');
UPDATE CREATURE_TABLE set aon_id = 1551, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Scarlet Triad Thug');
UPDATE CREATURE_TABLE set aon_id = 1552, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Mercenary Sailor');
UPDATE CREATURE_TABLE set aon_id = 1553, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Scarlet Triad Bruiser');
UPDATE CREATURE_TABLE set aon_id = 1554, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Scarlet Triad Poisoner');
UPDATE CREATURE_TABLE set aon_id = 1555, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Barushak Il-Varashma');
UPDATE CREATURE_TABLE set aon_id = 1559, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Scarlet Triad Sniper');
UPDATE CREATURE_TABLE set aon_id = 1560, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Laslunn');
UPDATE CREATURE_TABLE set aon_id = 1561, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Mialari Docur');
UPDATE CREATURE_TABLE set aon_id = 1562, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Nolly Peltry');
UPDATE CREATURE_TABLE set aon_id = 1566, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Kralgurn');
UPDATE CREATURE_TABLE set aon_id = 1567, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Scarlet Triad Agent');
UPDATE CREATURE_TABLE set aon_id = 1569, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Zuferian');
UPDATE CREATURE_TABLE set aon_id = 1574, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Duergar Slave Lord');
UPDATE CREATURE_TABLE set aon_id = 1575, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Kelda Halrig');
UPDATE CREATURE_TABLE set aon_id = 1576, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Ilssrah Embermead');
UPDATE CREATURE_TABLE set aon_id = 1579, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Scarlet Triad Enforcer');
UPDATE CREATURE_TABLE set aon_id = 1581, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Zephyr Guard');
UPDATE CREATURE_TABLE set aon_id = 1582, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Scarlet Triad Boss');
UPDATE CREATURE_TABLE set aon_id = 1583, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Scarlet Triad Mage');
UPDATE CREATURE_TABLE set aon_id = 1585, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Uri Zandivar');
UPDATE CREATURE_TABLE set aon_id = 1589, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Rinnarv Bontimar');
UPDATE CREATURE_TABLE set aon_id = 1590, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Promise Guard');
UPDATE CREATURE_TABLE set aon_id = 1595, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Ilgreth');
UPDATE CREATURE_TABLE set aon_id = 1597, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Emaliza Zandivar');
UPDATE CREATURE_TABLE set aon_id = 1598, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Inizra Arumelo');
UPDATE CREATURE_TABLE set aon_id = 1600, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Renali');
UPDATE CREATURE_TABLE set aon_id = 1629, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Mashkudu The Bully');
UPDATE CREATURE_TABLE set aon_id = 1630, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Kiru');
UPDATE CREATURE_TABLE set aon_id = 1631, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Loakan');
UPDATE CREATURE_TABLE set aon_id = 1632, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Reth');
UPDATE CREATURE_TABLE set aon_id = 1635, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Kolbo');
UPDATE CREATURE_TABLE set aon_id = 1646, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Keznin Nevarmo');
UPDATE CREATURE_TABLE set aon_id = 1647, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Gray Gardener Enforcer');
UPDATE CREATURE_TABLE set aon_id = 1648, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Gray Gardener Assassin');
UPDATE CREATURE_TABLE set aon_id = 1649, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Gray Gardener Director General');
UPDATE CREATURE_TABLE set aon_id = 1651, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Worm Prophet');
UPDATE CREATURE_TABLE set aon_id = 1680, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Onyiji');
UPDATE CREATURE_TABLE set aon_id = 1686, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Abendego Brute');
UPDATE CREATURE_TABLE set aon_id = 1687, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Abendego Jailer');
UPDATE CREATURE_TABLE set aon_id = 1688, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Yonsuu');
UPDATE CREATURE_TABLE set aon_id = 1689, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Abendego Priest');
UPDATE CREATURE_TABLE set aon_id = 1691, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Norgorberite Spy');
UPDATE CREATURE_TABLE set aon_id = 1695, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Jackal Guard');
UPDATE CREATURE_TABLE set aon_id = 1705, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Sun Warrior Brigade');
UPDATE CREATURE_TABLE set aon_id = 1711, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Mpondo');
UPDATE CREATURE_TABLE set aon_id = 1718, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Skartitch Chip-Tooth');
UPDATE CREATURE_TABLE set aon_id = 1719, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Crimson Acolyte');
UPDATE CREATURE_TABLE set aon_id = 1762, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Burnbearer');
UPDATE CREATURE_TABLE set aon_id = 1763, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Burning Mammoth Longshield');
UPDATE CREATURE_TABLE set aon_id = 1766, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Ardissa Prendergant');
UPDATE CREATURE_TABLE set aon_id = 1768, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Burning Mammoth Reaver');
UPDATE CREATURE_TABLE set aon_id = 1784, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Turkek');
UPDATE CREATURE_TABLE set aon_id = 1785, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Varilyn "Vare" Eridge');
UPDATE CREATURE_TABLE set aon_id = 1786, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Desiak');
UPDATE CREATURE_TABLE set aon_id = 1787, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Azi');
UPDATE CREATURE_TABLE set aon_id = 1788, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER("Venexus's Chosen");
UPDATE CREATURE_TABLE set aon_id = 1791, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Ashen Swale');
UPDATE CREATURE_TABLE set aon_id = 1792, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Idovik');
UPDATE CREATURE_TABLE set aon_id = 1803, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Unshadowed Okoro');
UPDATE CREATURE_TABLE set aon_id = 1805, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Unshadowed Mariama');
UPDATE CREATURE_TABLE set aon_id = 1807, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Unshadowed Anchor Root');
UPDATE CREATURE_TABLE set aon_id = 1808, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Unshadowed Haibram');
UPDATE CREATURE_TABLE set aon_id = 1820, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Yana No-trail');
UPDATE CREATURE_TABLE set aon_id = 1827, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Burning Mammoth Commando');
UPDATE CREATURE_TABLE set aon_id = 1828, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Jesseri The Hailstorm');
UPDATE CREATURE_TABLE set aon_id = 1830, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Lomok');
UPDATE CREATURE_TABLE set aon_id = 1932, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Gold Tank Investor');
UPDATE CREATURE_TABLE set aon_id = 1933, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Irkem Dresh');
UPDATE CREATURE_TABLE set aon_id = 1936, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Powderkeg Punk Bombardier');
UPDATE CREATURE_TABLE set aon_id = 1937, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Powderkeg Punk Gunner');
UPDATE CREATURE_TABLE set aon_id = 1938, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Dewey Daystar');
UPDATE CREATURE_TABLE set aon_id = 1939, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Gunmarshal');
UPDATE CREATURE_TABLE set aon_id = 1956, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Abridan Ashau');
UPDATE CREATURE_TABLE set aon_id = 1959, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Yniesse Zenderholm');
UPDATE CREATURE_TABLE set aon_id = 1960, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Acolyte of Pharasma');
UPDATE CREATURE_TABLE set aon_id = 1965, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Gilded Gunner Goon');
UPDATE CREATURE_TABLE set aon_id = 1966, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER("""Lucky"" Lanks");
UPDATE CREATURE_TABLE set aon_id = 1970, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Palzu');
UPDATE CREATURE_TABLE set aon_id = 1974, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Gilded Gunner Assassin');
UPDATE CREATURE_TABLE set aon_id = 1975, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Gilded Gunner Safecracker');
UPDATE CREATURE_TABLE set aon_id = 1987, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Leadsmith');
UPDATE CREATURE_TABLE set aon_id = 1995, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Abberton Ruffian');
UPDATE CREATURE_TABLE set aon_id = 1999, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Pruana Two-punch');
UPDATE CREATURE_TABLE set aon_id = 2001, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Daring Danika');
UPDATE CREATURE_TABLE set aon_id = 2003, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Jellico Bounce-Bounce');
UPDATE CREATURE_TABLE set aon_id = 2004, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Corrupted Retainer');
UPDATE CREATURE_TABLE set aon_id = 2006, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Corrupted Priest');
UPDATE CREATURE_TABLE set aon_id = 2012, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Nemmia Bramblecloak');
UPDATE CREATURE_TABLE set aon_id = 2013, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Viktor Volkano');
UPDATE CREATURE_TABLE set aon_id = 2014, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Aives The Smoke Dragon');
UPDATE CREATURE_TABLE set aon_id = 2015, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Delamar Gianvin');
UPDATE CREATURE_TABLE set aon_id = 2016, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Ruanna Nyamma');
UPDATE CREATURE_TABLE set aon_id = 2020, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Celestial Menagerie Bruiser');
UPDATE CREATURE_TABLE set aon_id = 2022, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Evora Yarket');
UPDATE CREATURE_TABLE set aon_id = 2023, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Darricus Stallit');
UPDATE CREATURE_TABLE set aon_id = 2025, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Mistress Dusklight');
UPDATE CREATURE_TABLE set aon_id = 2037, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Mother Mitera');
UPDATE CREATURE_TABLE set aon_id = 2044, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Sahreg the Dirge Screamer');
UPDATE CREATURE_TABLE set aon_id = 2047, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Crooked Coffin Brewer');
UPDATE CREATURE_TABLE set aon_id = 2061, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Sallowdrudge');
UPDATE CREATURE_TABLE set aon_id = 2068, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Teaching Assistant');
UPDATE CREATURE_TABLE set aon_id = 2088, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Nwanyian Archer');
UPDATE CREATURE_TABLE set aon_id = 2089, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Nwanyian Defender');
UPDATE CREATURE_TABLE set aon_id = 2090, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Zuntishan Guard');
UPDATE CREATURE_TABLE set aon_id = 2100, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Swardlands Delinquent');
UPDATE CREATURE_TABLE set aon_id = 2102, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Bitter Truth Bandit');
UPDATE CREATURE_TABLE set aon_id = 2103, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Pin Tingwheely');
UPDATE CREATURE_TABLE set aon_id = 2117, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Stirvyn Banyan');
UPDATE CREATURE_TABLE set aon_id = 2118, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Tashlock Banyan');
UPDATE CREATURE_TABLE set aon_id = 2126, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Ledorick Banyan');
UPDATE CREATURE_TABLE set aon_id = 2137, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Convergent Soldier');
UPDATE CREATURE_TABLE set aon_id = 2141, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Convergent Kendley Nathrael');
UPDATE CREATURE_TABLE set aon_id = 2148, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Rumin Purgo');
UPDATE CREATURE_TABLE set aon_id = 2163, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Gurtlekep');
UPDATE CREATURE_TABLE set aon_id = 2164, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Ygrik');
UPDATE CREATURE_TABLE set aon_id = 2165, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Edgrin Galesong');
UPDATE CREATURE_TABLE set aon_id = 2166, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Kerrdremak');
UPDATE CREATURE_TABLE set aon_id = 2167, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Lekmek');
UPDATE CREATURE_TABLE set aon_id = 2168, cr_type = 'Npc', family = 'Kobold' WHERE UPPER(name) = UPPER('Dark Talon Kobold');
UPDATE CREATURE_TABLE set aon_id = 2169, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Kapmek');
UPDATE CREATURE_TABLE set aon_id = 2170, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Jekkajak');
UPDATE CREATURE_TABLE set aon_id = 2188, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Armag Twice-Born');
UPDATE CREATURE_TABLE set aon_id = 2189, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Castruccio Irovetti');
UPDATE CREATURE_TABLE set aon_id = 2190, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Darivan');
UPDATE CREATURE_TABLE set aon_id = 2191, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Foras');
UPDATE CREATURE_TABLE set aon_id = 2192, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Grigori');
UPDATE CREATURE_TABLE set aon_id = 2193, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Hannis Drelev');
UPDATE CREATURE_TABLE set aon_id = 2195, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Jamandi Aldori');
UPDATE CREATURE_TABLE set aon_id = 2198, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('The Stag Lord');
UPDATE CREATURE_TABLE set aon_id = 2199, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Tartuccio');
UPDATE CREATURE_TABLE set aon_id = 2217, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Black Tear Cutthroat');
UPDATE CREATURE_TABLE set aon_id = 2220, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Nishkiv the Knife');
UPDATE CREATURE_TABLE set aon_id = 2221, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Volodmyra');
UPDATE CREATURE_TABLE set aon_id = 2222, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Oleg');
UPDATE CREATURE_TABLE set aon_id = 2223, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Svetlana');
UPDATE CREATURE_TABLE set aon_id = 2228, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Corax');
UPDATE CREATURE_TABLE set aon_id = 2229, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Logger');
UPDATE CREATURE_TABLE set aon_id = 2231, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Hateful Hermit');
UPDATE CREATURE_TABLE set aon_id = 2232, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Elga Verniex');
UPDATE CREATURE_TABLE set aon_id = 2263, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Ilora Nuski');
UPDATE CREATURE_TABLE set aon_id = 2269, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Chief Sootscale');
UPDATE CREATURE_TABLE set aon_id = 2272, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('King Vesket');
UPDATE CREATURE_TABLE set aon_id = 2278, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Happs Bydon');
UPDATE CREATURE_TABLE set aon_id = 2280, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Kressle');
UPDATE CREATURE_TABLE set aon_id = 2282, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Auchs');
UPDATE CREATURE_TABLE set aon_id = 2283, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Dovan from Nisroch');
UPDATE CREATURE_TABLE set aon_id = 2284, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Akiros Ismort');
UPDATE CREATURE_TABLE set aon_id = 2285, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Nugrah');
UPDATE CREATURE_TABLE set aon_id = 2287, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Kereek');
UPDATE CREATURE_TABLE set aon_id = 2288, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Prazil');
UPDATE CREATURE_TABLE set aon_id = 2289, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Malgorzata Niska');
UPDATE CREATURE_TABLE set aon_id = 2293, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Annamede Belavarah');
UPDATE CREATURE_TABLE set aon_id = 2303, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Aecora Silverfire');
UPDATE CREATURE_TABLE set aon_id = 2307, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Ameon Trask');
UPDATE CREATURE_TABLE set aon_id = 2309, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Satinder Morne');
UPDATE CREATURE_TABLE set aon_id = 2311, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Imeckus Stroon');
UPDATE CREATURE_TABLE set aon_id = 2312, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Pavetta Stroon-Drelev');
UPDATE CREATURE_TABLE set aon_id = 2314, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Quintessa Maray');
UPDATE CREATURE_TABLE set aon_id = 2315, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Terrion Numesti');
UPDATE CREATURE_TABLE set aon_id = 2321, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Zorek');
UPDATE CREATURE_TABLE set aon_id = 2331, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Villamor Koth');
UPDATE CREATURE_TABLE set aon_id = 2375, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Nilak');
UPDATE CREATURE_TABLE set aon_id = 2377, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Ntavi');
UPDATE CREATURE_TABLE set aon_id = 2379, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Eobald');
UPDATE CREATURE_TABLE set aon_id = 2384, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('The First Faithful');
UPDATE CREATURE_TABLE set aon_id = 2385, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Sir Fredero Sinnet');
UPDATE CREATURE_TABLE set aon_id = 2428, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Rival Corpsekiller');
UPDATE CREATURE_TABLE set aon_id = 2429, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Rival Necromancer');
UPDATE CREATURE_TABLE set aon_id = 2433, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Bellator Mortus Soldier');
UPDATE CREATURE_TABLE set aon_id = 2438, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Ruby');
UPDATE CREATURE_TABLE set aon_id = 2439, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Firebrand Bastion');
UPDATE CREATURE_TABLE set aon_id = 2449, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Bolan Nogasso');
UPDATE CREATURE_TABLE set aon_id = 2466, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Ghodrak the Quick');
UPDATE CREATURE_TABLE set aon_id = 2468, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Miriel Grayleaf');
UPDATE CREATURE_TABLE set aon_id = 2469, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Bolar Of Stonemoor');
UPDATE CREATURE_TABLE set aon_id = 2470, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Antaro Boldblade');
UPDATE CREATURE_TABLE set aon_id = 2471, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Skebs');
UPDATE CREATURE_TABLE set aon_id = 2472, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Eunice');
UPDATE CREATURE_TABLE set aon_id = 2474, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Battle Leader Rekarek');
UPDATE CREATURE_TABLE set aon_id = 2475, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Kekker');
UPDATE CREATURE_TABLE set aon_id = 2476, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Gref');
UPDATE CREATURE_TABLE set aon_id = 2479, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Kemeneles');
UPDATE CREATURE_TABLE set aon_id = 2480, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Lyrma Swampwalker');
UPDATE CREATURE_TABLE set aon_id = 2483, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Hendrid Pratchett');
UPDATE CREATURE_TABLE set aon_id = 2484, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Ralso');
UPDATE CREATURE_TABLE set aon_id = 2485, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Copper Hand Rogue');
UPDATE CREATURE_TABLE set aon_id = 2486, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Kolo Harvan');
UPDATE CREATURE_TABLE set aon_id = 2487, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Copper Hand Illusionist');
UPDATE CREATURE_TABLE set aon_id = 2488, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Fayati Alummur');
UPDATE CREATURE_TABLE set aon_id = 2492, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Skinsaw Murderer');
UPDATE CREATURE_TABLE set aon_id = 2493, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Skinsaw Seamer');
UPDATE CREATURE_TABLE set aon_id = 2494, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Wrent Dicaspiron');
UPDATE CREATURE_TABLE set aon_id = 2495, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Shristi Melipdra');
UPDATE CREATURE_TABLE set aon_id = 2505, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Snowy Owl');
UPDATE CREATURE_TABLE set aon_id = 2508, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Ilverani Sentry');
UPDATE CREATURE_TABLE set aon_id = 2533, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Scorching Sun Cultist');
UPDATE CREATURE_TABLE set aon_id = 2534, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Jimbilin');
UPDATE CREATURE_TABLE set aon_id = 2535, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Noolik');
UPDATE CREATURE_TABLE set aon_id = 2536, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Usij Cultist');
UPDATE CREATURE_TABLE set aon_id = 2537, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Krashk');
UPDATE CREATURE_TABLE set aon_id = 2540, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Amar');
UPDATE CREATURE_TABLE set aon_id = 2543, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Mercenary Assassin');
UPDATE CREATURE_TABLE set aon_id = 2544, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Vharnev the Butcher');
UPDATE CREATURE_TABLE set aon_id = 2545, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Raskus');
UPDATE CREATURE_TABLE set aon_id = 2546, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Mivanian Soldier');
UPDATE CREATURE_TABLE set aon_id = 2547, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Scaleseed Nagaji');
UPDATE CREATURE_TABLE set aon_id = 2549, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Shaldar Falls-Far');
UPDATE CREATURE_TABLE set aon_id = 2550, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Endlo Kiver');
UPDATE CREATURE_TABLE set aon_id = 2551, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Blade Mercenary');
UPDATE CREATURE_TABLE set aon_id = 2554, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Blade Magus');
UPDATE CREATURE_TABLE set aon_id = 2607, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Krohan Veldollow');
UPDATE CREATURE_TABLE set aon_id = 2717, cr_type = 'Npc', family = 'Duergar' WHERE UPPER(name) = UPPER('Hryngar Battlepriest');
UPDATE CREATURE_TABLE set aon_id = 2718, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Hrungul Ironeye');
UPDATE CREATURE_TABLE set aon_id = 2719, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Narseigus Wormcaller');
UPDATE CREATURE_TABLE set aon_id = 2737, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Ordwi');
UPDATE CREATURE_TABLE set aon_id = 2738, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Fallen Acolyte');
UPDATE CREATURE_TABLE set aon_id = 2739, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Trygve');
UPDATE CREATURE_TABLE set aon_id = 2740, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Vanda');
UPDATE CREATURE_TABLE set aon_id = 2742, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Rustsworn Initiate');
UPDATE CREATURE_TABLE set aon_id = 2743, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Knurr Ragnulf');
UPDATE CREATURE_TABLE set aon_id = 2749, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Meitremar');
UPDATE CREATURE_TABLE set aon_id = 2759, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Xin Yue');
UPDATE CREATURE_TABLE set aon_id = 2760, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Zhi Hui');
UPDATE CREATURE_TABLE set aon_id = 2797, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Heh Shan-Bao');
UPDATE CREATURE_TABLE set aon_id = 2798, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Mago Kai');
UPDATE CREATURE_TABLE set aon_id = 2806, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Heh Shan-Bao');
UPDATE CREATURE_TABLE set aon_id = 2807, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Ren Mei Li');
UPDATE CREATURE_TABLE set aon_id = 2869, cr_type = 'Npc', family = 'Catfolk' WHERE UPPER(name) = UPPER('Catfolk Pouncer');
UPDATE CREATURE_TABLE set aon_id = 2874, cr_type = 'Npc', family = 'Centaur' WHERE UPPER(name) = UPPER('Centaur Herbalist');
UPDATE CREATURE_TABLE set aon_id = 2913, cr_type = 'Npc', family = 'Dhampir' WHERE UPPER(name) = UPPER('Dhampir Wizard');
UPDATE CREATURE_TABLE set aon_id = 2965, cr_type = 'Npc', family = 'Dwarf' WHERE UPPER(name) = UPPER('Dwarf Warrior');
UPDATE CREATURE_TABLE set aon_id = 2966, cr_type = 'Npc', family = 'Dwarf' WHERE UPPER(name) = UPPER('Dwarf Stonecaster');
UPDATE CREATURE_TABLE set aon_id = 2995, cr_type = 'Npc', family = 'Elf' WHERE UPPER(name) = UPPER('Elf Ranger');
UPDATE CREATURE_TABLE set aon_id = 2996, cr_type = 'Npc', family = 'Elf' WHERE UPPER(name) = UPPER('Aiuvarin Elementalist');
UPDATE CREATURE_TABLE set aon_id = 3020, cr_type = 'Npc', family = 'Gnome' WHERE UPPER(name) = UPPER('Gnome Bard');
UPDATE CREATURE_TABLE set aon_id = 3021, cr_type = 'Npc', family = 'Gnome' WHERE UPPER(name) = UPPER('Umbral Gnome Scout');
UPDATE CREATURE_TABLE set aon_id = 3022, cr_type = 'Npc', family = 'Gnome' WHERE UPPER(name) = UPPER('Umbral Gnome Warrior');
UPDATE CREATURE_TABLE set aon_id = 3023, cr_type = 'Npc', family = 'Gnome' WHERE UPPER(name) = UPPER('Umbral Gnome Rockwarden');
UPDATE CREATURE_TABLE set aon_id = 3024, cr_type = 'Npc', family = 'Goblin' WHERE UPPER(name) = UPPER('Goblin Warrior');
UPDATE CREATURE_TABLE set aon_id = 3025, cr_type = 'Npc', family = 'Goblin' WHERE UPPER(name) = UPPER('Goblin Commando');
UPDATE CREATURE_TABLE set aon_id = 3026, cr_type = 'Npc', family = 'Goblin' WHERE UPPER(name) = UPPER('Goblin Pyro');
UPDATE CREATURE_TABLE set aon_id = 3027, cr_type = 'Npc', family = 'Goblin' WHERE UPPER(name) = UPPER('Goblin War Chanter');
UPDATE CREATURE_TABLE set aon_id = 3072, cr_type = 'Npc', family = 'Kobold' WHERE UPPER(name) = UPPER('Kobold Warrior');
UPDATE CREATURE_TABLE set aon_id = 3073, cr_type = 'Npc', family = 'Kobold' WHERE UPPER(name) = UPPER('Kobold Scout');
UPDATE CREATURE_TABLE set aon_id = 3074, cr_type = 'Npc', family = 'Kobold' WHERE UPPER(name) = UPPER('Kobold Cavern Mage');
UPDATE CREATURE_TABLE set aon_id = 3079, cr_type = 'Npc', family = 'Leshy' WHERE UPPER(name) = UPPER('Leaf Leshy');
UPDATE CREATURE_TABLE set aon_id = 3080, cr_type = 'Npc', family = 'Leshy' WHERE UPPER(name) = UPPER('Gourd Leshy');
UPDATE CREATURE_TABLE set aon_id = 3081, cr_type = 'Npc', family = 'Leshy' WHERE UPPER(name) = UPPER('Fungus Leshy');
UPDATE CREATURE_TABLE set aon_id = 3090, cr_type = 'Npc', family = 'Lizardfolk' WHERE UPPER(name) = UPPER('Lizardfolk Defender');
UPDATE CREATURE_TABLE set aon_id = 3091, cr_type = 'Npc', family = 'Lizardfolk' WHERE UPPER(name) = UPPER('Lizardfolk Scout');
UPDATE CREATURE_TABLE set aon_id = 3092, cr_type = 'Npc', family = 'Lizardfolk' WHERE UPPER(name) = UPPER('Lizardfolk Stargazer');
UPDATE CREATURE_TABLE set aon_id = 3129, cr_type = 'Npc', family = 'Orc' WHERE UPPER(name) = UPPER('Orc Scrapper');
UPDATE CREATURE_TABLE set aon_id = 3130, cr_type = 'Npc', family = 'Orc' WHERE UPPER(name) = UPPER('Orc Veteran');
UPDATE CREATURE_TABLE set aon_id = 3131, cr_type = 'Npc', family = 'Orc' WHERE UPPER(name) = UPPER('Dromaar Mountaineer');
UPDATE CREATURE_TABLE set aon_id = 3132, cr_type = 'Npc', family = 'Orc' WHERE UPPER(name) = UPPER('Orc Commander');
UPDATE CREATURE_TABLE set aon_id = 3140, cr_type = 'Npc', family = 'Planar Scion' WHERE UPPER(name) = UPPER('Pitborn Adept');
UPDATE CREATURE_TABLE set aon_id = 3141, cr_type = 'Npc', family = 'Planar Scion' WHERE UPPER(name) = UPPER('Lawbringer Warpriest');
UPDATE CREATURE_TABLE set aon_id = 3164, cr_type = 'Npc', family = 'Ratfolk' WHERE UPPER(name) = UPPER('Ratfolk Grenadier');
UPDATE CREATURE_TABLE set aon_id = 3214, cr_type = 'Npc', family = 'Tengu' WHERE UPPER(name) = UPPER('Tengu Sneak');
UPDATE CREATURE_TABLE set aon_id = 3370, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Kanker');
UPDATE CREATURE_TABLE set aon_id = 3378, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Talaro');
UPDATE CREATURE_TABLE set aon_id = 3379, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Red Mantis Assassin');
UPDATE CREATURE_TABLE set aon_id = 3380, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Red Mantis Conspirator');
UPDATE CREATURE_TABLE set aon_id = 3381, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Sister Maeri');
UPDATE CREATURE_TABLE set aon_id = 3382, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Mantis Keeper');
UPDATE CREATURE_TABLE set aon_id = 3383, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Shirota');
UPDATE CREATURE_TABLE set aon_id = 3384, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Zaiho');
UPDATE CREATURE_TABLE set aon_id = 3386, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Dronuk');
UPDATE CREATURE_TABLE set aon_id = 3387, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Rhysaphine');
UPDATE CREATURE_TABLE set aon_id = 3411, cr_type = 'Npc', family = 'Artisan' WHERE UPPER(name) = UPPER('Apprentice');
UPDATE CREATURE_TABLE set aon_id = 3412, cr_type = 'Npc', family = 'Artisan' WHERE UPPER(name) = UPPER('Merchant');
UPDATE CREATURE_TABLE set aon_id = 3413, cr_type = 'Npc', family = 'Artisan' WHERE UPPER(name) = UPPER('Smith');
UPDATE CREATURE_TABLE set aon_id = 3414, cr_type = 'Npc', family = 'Artisan' WHERE UPPER(name) = UPPER('Guildmaster');
UPDATE CREATURE_TABLE set aon_id = 3415, cr_type = 'Npc', family = 'Courtier' WHERE UPPER(name) = UPPER('Court Historian');
UPDATE CREATURE_TABLE set aon_id = 3416, cr_type = 'Npc', family = 'Courtier' WHERE UPPER(name) = UPPER('Envoy');
UPDATE CREATURE_TABLE set aon_id = 3418, cr_type = 'Npc', family = 'Courtier' WHERE UPPER(name) = UPPER('Noble');
UPDATE CREATURE_TABLE set aon_id = 3419, cr_type = 'Npc', family = 'Courtier' WHERE UPPER(name) = UPPER('Palace Guard');
UPDATE CREATURE_TABLE set aon_id = 3420, cr_type = 'Npc', family = 'Courtier' WHERE UPPER(name) = UPPER('Advisor');
UPDATE CREATURE_TABLE set aon_id = 3421, cr_type = 'Npc', family = 'Courtier' WHERE UPPER(name) = UPPER('Spy');
UPDATE CREATURE_TABLE set aon_id = 3422, cr_type = 'Npc', family = 'Courtier' WHERE UPPER(name) = UPPER('Veteran Noble');
UPDATE CREATURE_TABLE set aon_id = 3423, cr_type = 'Npc', family = 'Courtier' WHERE UPPER(name) = UPPER('Knight');
UPDATE CREATURE_TABLE set aon_id = 3424, cr_type = 'Npc', family = 'Criminal' WHERE UPPER(name) = UPPER('Grave Robber');
UPDATE CREATURE_TABLE set aon_id = 3425, cr_type = 'Npc', family = 'Criminal' WHERE UPPER(name) = UPPER('Bandit');
UPDATE CREATURE_TABLE set aon_id = 3426, cr_type = 'Npc', family = 'Criminal' WHERE UPPER(name) = UPPER('Loan Shark');
UPDATE CREATURE_TABLE set aon_id = 3427, cr_type = 'Npc', family = 'Criminal' WHERE UPPER(name) = UPPER('Ruffian');
UPDATE CREATURE_TABLE set aon_id = 3428, cr_type = 'Npc', family = 'Criminal' WHERE UPPER(name) = UPPER('Charlatan');
UPDATE CREATURE_TABLE set aon_id = 3429, cr_type = 'Npc', family = 'Criminal' WHERE UPPER(name) = UPPER('Burglar');
UPDATE CREATURE_TABLE set aon_id = 3430, cr_type = 'Npc', family = 'Criminal' WHERE UPPER(name) = UPPER('Fence');
UPDATE CREATURE_TABLE set aon_id = 3431, cr_type = 'Npc', family = 'Criminal' WHERE UPPER(name) = UPPER('Legbreaker');
UPDATE CREATURE_TABLE set aon_id = 3432, cr_type = 'Npc', family = 'Criminal' WHERE UPPER(name) = UPPER('Bandit Gang');
UPDATE CREATURE_TABLE set aon_id = 3433, cr_type = 'Npc', family = 'Criminal' WHERE UPPER(name) = UPPER('Master of Disguise');
UPDATE CREATURE_TABLE set aon_id = 3434, cr_type = 'Npc', family = 'Criminal' WHERE UPPER(name) = UPPER('Assassin');
UPDATE CREATURE_TABLE set aon_id = 3435, cr_type = 'Npc', family = 'Criminal' WHERE UPPER(name) = UPPER('Crime Kingpin');
UPDATE CREATURE_TABLE set aon_id = 3436, cr_type = 'Npc', family = 'Criminal' WHERE UPPER(name) = UPPER('Flamboyant Thief');
UPDATE CREATURE_TABLE set aon_id = 3437, cr_type = 'Npc', family = 'Devotee' WHERE UPPER(name) = UPPER('Pilgrim of Irori');
UPDATE CREATURE_TABLE set aon_id = 3438, cr_type = 'Npc', family = 'Devotee' WHERE UPPER(name) = UPPER('Penitent of Calistria');
UPDATE CREATURE_TABLE set aon_id = 3439, cr_type = 'Npc', family = 'Devotee' WHERE UPPER(name) = UPPER('Abbot of Abadar');
UPDATE CREATURE_TABLE set aon_id = 3440, cr_type = 'Npc', family = 'Devotee' WHERE UPPER(name) = UPPER('Acolyte of Iomedae');
UPDATE CREATURE_TABLE set aon_id = 3441, cr_type = 'Npc', family = 'Devotee' WHERE UPPER(name) = UPPER('Blasphemer of Zon-Kuthon');
UPDATE CREATURE_TABLE set aon_id = 3442, cr_type = 'Npc', family = 'Devotee' WHERE UPPER(name) = UPPER('Prophet');
UPDATE CREATURE_TABLE set aon_id = 3443, cr_type = 'Npc', family = 'Devotee' WHERE UPPER(name) = UPPER('Sibyl');
UPDATE CREATURE_TABLE set aon_id = 3444, cr_type = 'Npc', family = 'Devotee' WHERE UPPER(name) = UPPER('Zealot of Asmodeus');
UPDATE CREATURE_TABLE set aon_id = 3445, cr_type = 'Npc', family = 'Devotee' WHERE UPPER(name) = UPPER('Priest of Sarenrae');
UPDATE CREATURE_TABLE set aon_id = 3446, cr_type = 'Npc', family = 'Devotee' WHERE UPPER(name) = UPPER('Champion of Shelyn');
UPDATE CREATURE_TABLE set aon_id = 3447, cr_type = 'Npc', family = 'Devotee' WHERE UPPER(name) = UPPER('High Priest of Pharasma');
UPDATE CREATURE_TABLE set aon_id = 3448, cr_type = 'Npc', family = 'Devotee' WHERE UPPER(name) = UPPER('Traveling Priest of Desna');
UPDATE CREATURE_TABLE set aon_id = 3449, cr_type = 'Npc', family = 'Devotee' WHERE UPPER(name) = UPPER('Rancorous Priesthood');
UPDATE CREATURE_TABLE set aon_id = 3450, cr_type = 'Npc', family = 'Devotee' WHERE UPPER(name) = UPPER('Deific Champion of Iomedae');
UPDATE CREATURE_TABLE set aon_id = 3451, cr_type = 'Npc', family = 'Devotee' WHERE UPPER(name) = UPPER('Deific Vessel of Urgathoa');
UPDATE CREATURE_TABLE set aon_id = 3452, cr_type = 'Npc', family = 'Downtrodden' WHERE UPPER(name) = UPPER('Beggar');
UPDATE CREATURE_TABLE set aon_id = 3453, cr_type = 'Npc', family = 'Downtrodden' WHERE UPPER(name) = UPPER('Urchin');
UPDATE CREATURE_TABLE set aon_id = 3454, cr_type = 'Npc', family = 'Downtrodden' WHERE UPPER(name) = UPPER('Prisoner');
UPDATE CREATURE_TABLE set aon_id = 3455, cr_type = 'Npc', family = 'Downtrodden' WHERE UPPER(name) = UPPER('Drunkard');
UPDATE CREATURE_TABLE set aon_id = 3456, cr_type = 'Npc', family = 'Engineer' WHERE UPPER(name) = UPPER('Gunsmith');
UPDATE CREATURE_TABLE set aon_id = 3457, cr_type = 'Npc', family = 'Engineer' WHERE UPPER(name) = UPPER('Mechanic');
UPDATE CREATURE_TABLE set aon_id = 3458, cr_type = 'Npc', family = 'Engineer' WHERE UPPER(name) = UPPER('Driver');
UPDATE CREATURE_TABLE set aon_id = 3459, cr_type = 'Npc', family = 'Engineer' WHERE UPPER(name) = UPPER('Artillerist');
UPDATE CREATURE_TABLE set aon_id = 3460, cr_type = 'Npc', family = 'Engineer' WHERE UPPER(name) = UPPER('Toymaker');
UPDATE CREATURE_TABLE set aon_id = 3461, cr_type = 'Npc', family = 'Engineer' WHERE UPPER(name) = UPPER('Demolitionist');
UPDATE CREATURE_TABLE set aon_id = 3462, cr_type = 'Npc', family = 'Engineer' WHERE UPPER(name) = UPPER('Gadgeteer');
UPDATE CREATURE_TABLE set aon_id = 3463, cr_type = 'Npc', family = 'Engineer' WHERE UPPER(name) = UPPER('Rocketeer');
UPDATE CREATURE_TABLE set aon_id = 3464, cr_type = 'Npc', family = 'Engineer' WHERE UPPER(name) = UPPER('Dynamo');
UPDATE CREATURE_TABLE set aon_id = 3465, cr_type = 'Npc', family = 'Engineer' WHERE UPPER(name) = UPPER('Juggernaut');
UPDATE CREATURE_TABLE set aon_id = 3466, cr_type = 'Npc', family = 'Explorer' WHERE UPPER(name) = UPPER('Torchbearer');
UPDATE CREATURE_TABLE set aon_id = 3468, cr_type = 'Npc', family = 'Explorer' WHERE UPPER(name) = UPPER('Natural Scientist');
UPDATE CREATURE_TABLE set aon_id = 3469, cr_type = 'Npc', family = 'Explorer' WHERE UPPER(name) = UPPER('Poacher');
UPDATE CREATURE_TABLE set aon_id = 3470, cr_type = 'Npc', family = 'Explorer' WHERE UPPER(name) = UPPER('Chronicler');
UPDATE CREATURE_TABLE set aon_id = 3471, cr_type = 'Npc', family = 'Explorer' WHERE UPPER(name) = UPPER('Tracker');
UPDATE CREATURE_TABLE set aon_id = 3472, cr_type = 'Npc', family = 'Explorer' WHERE UPPER(name) = UPPER('Guide');
UPDATE CREATURE_TABLE set aon_id = 3473, cr_type = 'Npc', family = 'Explorer' WHERE UPPER(name) = UPPER('Mountaineer');
UPDATE CREATURE_TABLE set aon_id = 3474, cr_type = 'Npc', family = 'Explorer' WHERE UPPER(name) = UPPER('Tomb Raider');
UPDATE CREATURE_TABLE set aon_id = 3475, cr_type = 'Npc', family = 'Explorer' WHERE UPPER(name) = UPPER('Gamekeeper');
UPDATE CREATURE_TABLE set aon_id = 3476, cr_type = 'Npc', family = 'Explorer' WHERE UPPER(name) = UPPER('Hunter');
UPDATE CREATURE_TABLE set aon_id = 3478, cr_type = 'Npc', family = 'Explorer' WHERE UPPER(name) = UPPER('Expedition Leader');
UPDATE CREATURE_TABLE set aon_id = 3479, cr_type = 'Npc', family = 'Healer' WHERE UPPER(name) = UPPER('Apothecary');
UPDATE CREATURE_TABLE set aon_id = 3480, cr_type = 'Npc', family = 'Healer' WHERE UPPER(name) = UPPER('Physician');
UPDATE CREATURE_TABLE set aon_id = 3481, cr_type = 'Npc', family = 'Healer' WHERE UPPER(name) = UPPER('Local Herbalist');
UPDATE CREATURE_TABLE set aon_id = 3482, cr_type = 'Npc', family = 'Healer' WHERE UPPER(name) = UPPER('Surgeon');
UPDATE CREATURE_TABLE set aon_id = 3483, cr_type = 'Npc', family = 'Healer' WHERE UPPER(name) = UPPER('Tonic Merchant');
UPDATE CREATURE_TABLE set aon_id = 3484, cr_type = 'Npc', family = 'Healer' WHERE UPPER(name) = UPPER('Plague Doctor');
UPDATE CREATURE_TABLE set aon_id = 3485, cr_type = 'Npc', family = 'Healer' WHERE UPPER(name) = UPPER('Therapeutic Healer');
UPDATE CREATURE_TABLE set aon_id = 3486, cr_type = 'Npc', family = 'Healer' WHERE UPPER(name) = UPPER('Humanitarian Hermit');
UPDATE CREATURE_TABLE set aon_id = 3487, cr_type = 'Npc', family = 'Healer' WHERE UPPER(name) = UPPER('Peerless Healer');
UPDATE CREATURE_TABLE set aon_id = 3488, cr_type = 'Npc', family = 'Laborer' WHERE UPPER(name) = UPPER('Commoner');
UPDATE CREATURE_TABLE set aon_id = 3489, cr_type = 'Npc', family = 'Laborer' WHERE UPPER(name) = UPPER('Servant');
UPDATE CREATURE_TABLE set aon_id = 3490, cr_type = 'Npc', family = 'Laborer' WHERE UPPER(name) = UPPER('Dockhand');
UPDATE CREATURE_TABLE set aon_id = 3491, cr_type = 'Npc', family = 'Laborer' WHERE UPPER(name) = UPPER('Drover');
UPDATE CREATURE_TABLE set aon_id = 3492, cr_type = 'Npc', family = 'Laborer' WHERE UPPER(name) = UPPER('Farmer');
UPDATE CREATURE_TABLE set aon_id = 3493, cr_type = 'Npc', family = 'Laborer' WHERE UPPER(name) = UPPER('Fisher');
UPDATE CREATURE_TABLE set aon_id = 3494, cr_type = 'Npc', family = 'Laborer' WHERE UPPER(name) = UPPER('Miner');
UPDATE CREATURE_TABLE set aon_id = 3495, cr_type = 'Npc', family = 'Laborer' WHERE UPPER(name) = UPPER('Gravedigger');
UPDATE CREATURE_TABLE set aon_id = 3496, cr_type = 'Npc', family = 'Laborer' WHERE UPPER(name) = UPPER('Innkeeper');
UPDATE CREATURE_TABLE set aon_id = 3497, cr_type = 'Npc', family = 'Laborer' WHERE UPPER(name) = UPPER('Messenger');
UPDATE CREATURE_TABLE set aon_id = 3498, cr_type = 'Npc', family = 'Laborer' WHERE UPPER(name) = UPPER('Construction Worker');
UPDATE CREATURE_TABLE set aon_id = 3499, cr_type = 'Npc', family = 'Laborer' WHERE UPPER(name) = UPPER('Vermin Catcher');
UPDATE CREATURE_TABLE set aon_id = 3500, cr_type = 'Npc', family = 'Martial Artist' WHERE UPPER(name) = UPPER('Martial Student');
UPDATE CREATURE_TABLE set aon_id = 3501, cr_type = 'Npc', family = 'Martial Artist' WHERE UPPER(name) = UPPER('Tournament Combatant');
UPDATE CREATURE_TABLE set aon_id = 3502, cr_type = 'Npc', family = 'Laborer' WHERE UPPER(name) = UPPER('Mixed Martial Artist');
UPDATE CREATURE_TABLE set aon_id = 3503, cr_type = 'Npc', family = 'Martial Artist' WHERE UPPER(name) = UPPER('Grandmaster');
UPDATE CREATURE_TABLE set aon_id = 3504, cr_type = 'Npc', family = 'Martial Artist' WHERE UPPER(name) = UPPER('Black Belt');
UPDATE CREATURE_TABLE set aon_id = 3505, cr_type = 'Npc', family = 'Maverick' WHERE UPPER(name) = UPPER('Political Upstart');
UPDATE CREATURE_TABLE set aon_id = 3506, cr_type = 'Npc', family = 'Maverick' WHERE UPPER(name) = UPPER('Arms Dealer');
UPDATE CREATURE_TABLE set aon_id = 3507, cr_type = 'Npc', family = 'Maverick' WHERE UPPER(name) = UPPER('Musketeer');
UPDATE CREATURE_TABLE set aon_id = 3508, cr_type = 'Npc', family = 'Maverick' WHERE UPPER(name) = UPPER('Runaway Blueblood');
UPDATE CREATURE_TABLE set aon_id = 3509, cr_type = 'Npc', family = 'Maverick' WHERE UPPER(name) = UPPER('Unsanctioned Sheriff');
UPDATE CREATURE_TABLE set aon_id = 3510, cr_type = 'Npc', family = 'Maverick' WHERE UPPER(name) = UPPER('Gunwitch');
UPDATE CREATURE_TABLE set aon_id = 3511, cr_type = 'Npc', family = 'Maverick' WHERE UPPER(name) = UPPER('High Roller');
UPDATE CREATURE_TABLE set aon_id = 3512, cr_type = 'Npc', family = 'Maverick' WHERE UPPER(name) = UPPER('Peerless Duelist');
UPDATE CREATURE_TABLE set aon_id = 3513, cr_type = 'Npc', family = 'Mercenary' WHERE UPPER(name) = UPPER('Bodyguard');
UPDATE CREATURE_TABLE set aon_id = 3514, cr_type = 'Npc', family = 'Mercenary' WHERE UPPER(name) = UPPER('Mage for Hire');
UPDATE CREATURE_TABLE set aon_id = 3515, cr_type = 'Npc', family = 'Mercenary' WHERE UPPER(name) = UPPER('Bounty Hunter');
UPDATE CREATURE_TABLE set aon_id = 3516, cr_type = 'Npc', family = 'Mercenary' WHERE UPPER(name) = UPPER('Monster Hunter');
UPDATE CREATURE_TABLE set aon_id = 3517, cr_type = 'Npc', family = 'Mercenary' WHERE UPPER(name) = UPPER('Mage Killer');
UPDATE CREATURE_TABLE set aon_id = 3518, cr_type = 'Npc', family = 'Mercenary' WHERE UPPER(name) = UPPER('Mercenary Band');
UPDATE CREATURE_TABLE set aon_id = 3519, cr_type = 'Npc', family = 'Mercenary' WHERE UPPER(name) = UPPER('Exiled Revolutionary');
UPDATE CREATURE_TABLE set aon_id = 3520, cr_type = 'Npc', family = 'Mercenary' WHERE UPPER(name) = UPPER('Siegebreaker');
UPDATE CREATURE_TABLE set aon_id = 3521, cr_type = 'Npc', family = 'Military' WHERE UPPER(name) = UPPER('Combat Engineer');
UPDATE CREATURE_TABLE set aon_id = 3522, cr_type = 'Npc', family = 'Military' WHERE UPPER(name) = UPPER('Infantry Soldier');
UPDATE CREATURE_TABLE set aon_id = 3523, cr_type = 'Npc', family = 'Military' WHERE UPPER(name) = UPPER('Conscript Squad');
UPDATE CREATURE_TABLE set aon_id = 3524, cr_type = 'Npc', family = 'Military' WHERE UPPER(name) = UPPER('Standard Bearer');
UPDATE CREATURE_TABLE set aon_id = 3525, cr_type = 'Npc', family = 'Military' WHERE UPPER(name) = UPPER('Sniper');
UPDATE CREATURE_TABLE set aon_id = 3526, cr_type = 'Npc', family = 'Military' WHERE UPPER(name) = UPPER('Line Infantry');
UPDATE CREATURE_TABLE set aon_id = 3527, cr_type = 'Npc', family = 'Military' WHERE UPPER(name) = UPPER('Phalanx Formation');
UPDATE CREATURE_TABLE set aon_id = 3528, cr_type = 'Npc', family = 'Military' WHERE UPPER(name) = UPPER('Heavy Cavalry');
UPDATE CREATURE_TABLE set aon_id = 3529, cr_type = 'Npc', family = 'Military' WHERE UPPER(name) = UPPER('Drill Sergeant');
UPDATE CREATURE_TABLE set aon_id = 3530, cr_type = 'Npc', family = 'Military' WHERE UPPER(name) = UPPER('Hellknight Cavalry Brigade');
UPDATE CREATURE_TABLE set aon_id = 3531, cr_type = 'Npc', family = 'Military' WHERE UPPER(name) = UPPER('Mage Knight');
UPDATE CREATURE_TABLE set aon_id = 3532, cr_type = 'Npc', family = 'Mystic' WHERE UPPER(name) = UPPER('Adept');
UPDATE CREATURE_TABLE set aon_id = 3533, cr_type = 'Npc', family = 'Mystic' WHERE UPPER(name) = UPPER('Harrow Reader');
UPDATE CREATURE_TABLE set aon_id = 3534, cr_type = 'Npc', family = 'Mystic' WHERE UPPER(name) = UPPER('Cultist');
UPDATE CREATURE_TABLE set aon_id = 3535, cr_type = 'Npc', family = 'Mystic' WHERE UPPER(name) = UPPER('Coven Aspirant');
UPDATE CREATURE_TABLE set aon_id = 3538, cr_type = 'Npc', family = 'Mystic' WHERE UPPER(name) = UPPER('Necromancer');
UPDATE CREATURE_TABLE set aon_id = 3539, cr_type = 'Npc', family = 'Mystic' WHERE UPPER(name) = UPPER('Cult Leader');
UPDATE CREATURE_TABLE set aon_id = 3540, cr_type = 'Npc', family = 'Mystic' WHERE UPPER(name) = UPPER('Demonologist');
UPDATE CREATURE_TABLE set aon_id = 3541, cr_type = 'Npc', family = 'Mystic' WHERE UPPER(name) = UPPER('Mirror Seer');
UPDATE CREATURE_TABLE set aon_id = 3542, cr_type = 'Npc', family = 'Mystic' WHERE UPPER(name) = UPPER('God Caller');
UPDATE CREATURE_TABLE set aon_id = 3543, cr_type = 'Npc', family = 'Mystic' WHERE UPPER(name) = UPPER('Spirit Binder');
UPDATE CREATURE_TABLE set aon_id = 3544, cr_type = 'Npc', family = 'Mystic' WHERE UPPER(name) = UPPER('Curse Monger');
UPDATE CREATURE_TABLE set aon_id = 3545, cr_type = 'Npc', family = 'Mystic' WHERE UPPER(name) = UPPER('Enchanting Ritualist');
UPDATE CREATURE_TABLE set aon_id = 3546, cr_type = 'Npc', family = 'Official' WHERE UPPER(name) = UPPER('Barrister');
UPDATE CREATURE_TABLE set aon_id = 3547, cr_type = 'Npc', family = 'Official' WHERE UPPER(name) = UPPER('Judge');
UPDATE CREATURE_TABLE set aon_id = 3548, cr_type = 'Npc', family = 'Official' WHERE UPPER(name) = UPPER('Tax Collector');
UPDATE CREATURE_TABLE set aon_id = 3549, cr_type = 'Npc', family = 'Official' WHERE UPPER(name) = UPPER('Mayor');
UPDATE CREATURE_TABLE set aon_id = 3550, cr_type = 'Npc', family = 'Official' WHERE UPPER(name) = UPPER('Prime Minister');
UPDATE CREATURE_TABLE set aon_id = 3551, cr_type = 'Npc', family = 'Official' WHERE UPPER(name) = UPPER('Guard');
UPDATE CREATURE_TABLE set aon_id = 3552, cr_type = 'Npc', family = 'Official' WHERE UPPER(name) = UPPER('Archer Sentry');
UPDATE CREATURE_TABLE set aon_id = 3553, cr_type = 'Npc', family = 'Official' WHERE UPPER(name) = UPPER('Harbormaster');
UPDATE CREATURE_TABLE set aon_id = 3554, cr_type = 'Npc', family = 'Official' WHERE UPPER(name) = UPPER('Inspector');
UPDATE CREATURE_TABLE set aon_id = 3555, cr_type = 'Npc', family = 'Official' WHERE UPPER(name) = UPPER('Jailer');
UPDATE CREATURE_TABLE set aon_id = 3556, cr_type = 'Npc', family = 'Official' WHERE UPPER(name) = UPPER('Watch Officer');
UPDATE CREATURE_TABLE set aon_id = 3557, cr_type = 'Npc', family = 'Official' WHERE UPPER(name) = UPPER('Equestrian Constable');
UPDATE CREATURE_TABLE set aon_id = 3558, cr_type = 'Npc', family = 'Official' WHERE UPPER(name) = UPPER('City Guard Squadron');
UPDATE CREATURE_TABLE set aon_id = 3559, cr_type = 'Npc', family = 'Official' WHERE UPPER(name) = UPPER('Watchmage');
UPDATE CREATURE_TABLE set aon_id = 3560, cr_type = 'Npc', family = 'Official' WHERE UPPER(name) = UPPER('Captain Of The Guard');
UPDATE CREATURE_TABLE set aon_id = 3561, cr_type = 'Npc', family = 'Official' WHERE UPPER(name) = UPPER('Executioner');
UPDATE CREATURE_TABLE set aon_id = 3562, cr_type = 'Npc', family = 'Official' WHERE UPPER(name) = UPPER('Warden');
UPDATE CREATURE_TABLE set aon_id = 3563, cr_type = 'Npc', family = 'Official' WHERE UPPER(name) = UPPER('Gendarme');
UPDATE CREATURE_TABLE set aon_id = 3564, cr_type = 'Npc', family = 'Official' WHERE UPPER(name) = UPPER('Arrester Squadron');
UPDATE CREATURE_TABLE set aon_id = 3565, cr_type = 'Npc', family = 'Official' WHERE UPPER(name) = UPPER('Accuser Agent');
UPDATE CREATURE_TABLE set aon_id = 3566, cr_type = 'Npc', family = 'Official' WHERE UPPER(name) = UPPER('Infernal Registrar');
UPDATE CREATURE_TABLE set aon_id = 3567, cr_type = 'Npc', family = 'Official' WHERE UPPER(name) = UPPER('Watchmage Squadron');
UPDATE CREATURE_TABLE set aon_id = 3568, cr_type = 'Npc', family = 'Official' WHERE UPPER(name) = UPPER('Grand Inquisitor');
UPDATE CREATURE_TABLE set aon_id = 3569, cr_type = 'Npc', family = 'Performer' WHERE UPPER(name) = UPPER('Dancer');
UPDATE CREATURE_TABLE set aon_id = 3570, cr_type = 'Npc', family = 'Performer' WHERE UPPER(name) = UPPER('Acrobat');
UPDATE CREATURE_TABLE set aon_id = 3571, cr_type = 'Npc', family = 'Performer' WHERE UPPER(name) = UPPER('Street Musician');
UPDATE CREATURE_TABLE set aon_id = 3572, cr_type = 'Npc', family = 'Performer' WHERE UPPER(name) = UPPER('Juggler');
UPDATE CREATURE_TABLE set aon_id = 3573, cr_type = 'Npc', family = 'Performer' WHERE UPPER(name) = UPPER('Mime');
UPDATE CREATURE_TABLE set aon_id = 3574, cr_type = 'Npc', family = 'Performer' WHERE UPPER(name) = UPPER('Traveling Actor');
UPDATE CREATURE_TABLE set aon_id = 3575, cr_type = 'Npc', family = 'Performer' WHERE UPPER(name) = UPPER('Troubadour');
UPDATE CREATURE_TABLE set aon_id = 3576, cr_type = 'Npc', family = 'Performer' WHERE UPPER(name) = UPPER('Beast Tamer');
UPDATE CREATURE_TABLE set aon_id = 3577, cr_type = 'Npc', family = 'Performer' WHERE UPPER(name) = UPPER('Puppeteer');
UPDATE CREATURE_TABLE set aon_id = 3578, cr_type = 'Npc', family = 'Performer' WHERE UPPER(name) = UPPER('Court Jester');
UPDATE CREATURE_TABLE set aon_id = 3579, cr_type = 'Npc', family = 'Performer' WHERE UPPER(name) = UPPER('Maestro');
UPDATE CREATURE_TABLE set aon_id = 3580, cr_type = 'Npc', family = 'Performer' WHERE UPPER(name) = UPPER('Druid Initiate');
UPDATE CREATURE_TABLE set aon_id = 3581, cr_type = 'Npc', family = 'Primalist' WHERE UPPER(name) = UPPER('Pack Leader');
UPDATE CREATURE_TABLE set aon_id = 3582, cr_type = 'Npc', family = 'Primalist' WHERE UPPER(name) = UPPER('Mountain Guardian');
UPDATE CREATURE_TABLE set aon_id = 3583, cr_type = 'Npc', family = 'Primalist' WHERE UPPER(name) = UPPER('Dedicated Druid');
UPDATE CREATURE_TABLE set aon_id = 3584, cr_type = 'Npc', family = 'Primalist' WHERE UPPER(name) = UPPER('Skin Shifter');
UPDATE CREATURE_TABLE set aon_id = 3585, cr_type = 'Npc', family = 'Primalist' WHERE UPPER(name) = UPPER('Tree Singer');
UPDATE CREATURE_TABLE set aon_id = 3586, cr_type = 'Npc', family = 'Primalist' WHERE UPPER(name) = UPPER('Tempest Incarnate');
UPDATE CREATURE_TABLE set aon_id = 3587, cr_type = 'Npc', family = 'Scholar' WHERE UPPER(name) = UPPER('Librarian');
UPDATE CREATURE_TABLE set aon_id = 3588, cr_type = 'Npc', family = 'Scholar' WHERE UPPER(name) = UPPER('Obsessive Researcher');
UPDATE CREATURE_TABLE set aon_id = 3589, cr_type = 'Npc', family = 'Scholar' WHERE UPPER(name) = UPPER('Teacher');
UPDATE CREATURE_TABLE set aon_id = 3590, cr_type = 'Npc', family = 'Scholar' WHERE UPPER(name) = UPPER('Astronomer');
UPDATE CREATURE_TABLE set aon_id = 3591, cr_type = 'Npc', family = 'Scholar' WHERE UPPER(name) = UPPER('Exuberant Apprentice');
UPDATE CREATURE_TABLE set aon_id = 3592, cr_type = 'Npc', family = 'Scholar' WHERE UPPER(name) = UPPER('Avuncular Professor');
UPDATE CREATURE_TABLE set aon_id = 3593, cr_type = 'Npc', family = 'Scholar' WHERE UPPER(name) = UPPER('Sage');
UPDATE CREATURE_TABLE set aon_id = 3594, cr_type = 'Npc', family = 'Scholar' WHERE UPPER(name) = UPPER('Departmental Chair');
UPDATE CREATURE_TABLE set aon_id = 3595, cr_type = 'Npc', family = 'Scholar' WHERE UPPER(name) = UPPER('Globetrotting Scholar');
UPDATE CREATURE_TABLE set aon_id = 3596, cr_type = 'Npc', family = 'Scholar' WHERE UPPER(name) = UPPER('Eldritch Emeritus');
UPDATE CREATURE_TABLE set aon_id = 3597, cr_type = 'Npc', family = 'Seafarer' WHERE UPPER(name) = UPPER('Rigger');
UPDATE CREATURE_TABLE set aon_id = 3598, cr_type = 'Npc', family = 'Seafarer' WHERE UPPER(name) = UPPER('Navigator');
UPDATE CREATURE_TABLE set aon_id = 3599, cr_type = 'Npc', family = 'Seafarer' WHERE UPPER(name) = UPPER('Pirate');
UPDATE CREATURE_TABLE set aon_id = 3600, cr_type = 'Npc', family = 'Seafarer' WHERE UPPER(name) = UPPER('Bosun');
UPDATE CREATURE_TABLE set aon_id = 3601, cr_type = 'Npc', family = 'Seafarer' WHERE UPPER(name) = UPPER('Diver');
UPDATE CREATURE_TABLE set aon_id = 3602, cr_type = 'Npc', family = 'Seafarer' WHERE UPPER(name) = UPPER('Castaway');
UPDATE CREATURE_TABLE set aon_id = 3603, cr_type = 'Npc', family = 'Seafarer' WHERE UPPER(name) = UPPER('Subaquatic Marauder');
UPDATE CREATURE_TABLE set aon_id = 3604, cr_type = 'Npc', family = 'Seafarer' WHERE UPPER(name) = UPPER('Ship Captain');
UPDATE CREATURE_TABLE set aon_id = 3605, cr_type = 'Npc', family = 'Seafarer' WHERE UPPER(name) = UPPER('Ocean Nomad');
UPDATE CREATURE_TABLE set aon_id = 3606, cr_type = 'Npc', family = 'Villain' WHERE UPPER(name) = UPPER('Conspiracist');
UPDATE CREATURE_TABLE set aon_id = 3607, cr_type = 'Npc', family = 'Villain' WHERE UPPER(name) = UPPER('Toady');
UPDATE CREATURE_TABLE set aon_id = 3608, cr_type = 'Npc', family = 'Villain' WHERE UPPER(name) = UPPER('Saboteur');
UPDATE CREATURE_TABLE set aon_id = 3609, cr_type = 'Npc', family = 'Villain' WHERE UPPER(name) = UPPER('Fiend Caller');
UPDATE CREATURE_TABLE set aon_id = 3610, cr_type = 'Npc', family = 'Villain' WHERE UPPER(name) = UPPER('Propagandist');
UPDATE CREATURE_TABLE set aon_id = 3611, cr_type = 'Npc', family = 'Villain' WHERE UPPER(name) = UPPER('Deluded Mob');
UPDATE CREATURE_TABLE set aon_id = 3612, cr_type = 'Npc', family = 'Villain' WHERE UPPER(name) = UPPER('Mastermind');
UPDATE CREATURE_TABLE set aon_id = 3613, cr_type = 'Npc', family = 'Villain' WHERE UPPER(name) = UPPER('Champion of Rovagug');
UPDATE CREATURE_TABLE set aon_id = 3614, cr_type = 'Npc', family = 'Villain' WHERE UPPER(name) = UPPER('Despot');
UPDATE CREATURE_TABLE set aon_id = 3615, cr_type = 'Npc', family = 'Villain' WHERE UPPER(name) = UPPER('Interrogator');
UPDATE CREATURE_TABLE set aon_id = 3616, cr_type = 'Npc', family = 'Villain' WHERE UPPER(name) = UPPER('Reckless Scientist');
UPDATE CREATURE_TABLE set aon_id = 3617, cr_type = 'Npc', family = 'Villain' WHERE UPPER(name) = UPPER('Fleshwarper');
UPDATE CREATURE_TABLE set aon_id = 3618, cr_type = 'Npc', family = 'Villain' WHERE UPPER(name) = UPPER('Gang Leader');
UPDATE CREATURE_TABLE set aon_id = 3619, cr_type = 'Npc', family = 'Villain' WHERE UPPER(name) = UPPER('Wealthy Vigilante');
UPDATE CREATURE_TABLE set aon_id = 3620, cr_type = 'Npc', family = 'Villain' WHERE UPPER(name) = UPPER('Warmonger');
UPDATE CREATURE_TABLE set aon_id = 3621, cr_type = 'Npc', family = 'Villain' WHERE UPPER(name) = UPPER('Hero Hunter');
UPDATE CREATURE_TABLE set aon_id = 3622, cr_type = 'Npc', family = 'Villain' WHERE UPPER(name) = UPPER('World Ender');
UPDATE CREATURE_TABLE set aon_id = 3623, cr_type = 'Npc', family = 'Catfolk' WHERE UPPER(name) = UPPER('Leaping Thief');
UPDATE CREATURE_TABLE set aon_id = 3624, cr_type = 'Npc', family = 'Catfolk' WHERE UPPER(name) = UPPER('Catfolk Name Collector');
UPDATE CREATURE_TABLE set aon_id = 3625, cr_type = 'Npc', family = 'Catfolk' WHERE UPPER(name) = UPPER('Lucky Courser');
UPDATE CREATURE_TABLE set aon_id = 3626, cr_type = 'Npc', family = 'Dwarf' WHERE UPPER(name) = UPPER('Dwarf Smith');
UPDATE CREATURE_TABLE set aon_id = 3627, cr_type = 'Npc', family = 'Dwarf' WHERE UPPER(name) = UPPER('Spirit Priest');
UPDATE CREATURE_TABLE set aon_id = 3628, cr_type = 'Npc', family = 'Dwarf' WHERE UPPER(name) = UPPER('Dwarf Battalion');
UPDATE CREATURE_TABLE set aon_id = 3629, cr_type = 'Npc', family = 'Dwarf' WHERE UPPER(name) = UPPER('Dwarf General');
UPDATE CREATURE_TABLE set aon_id = 3630, cr_type = 'Npc', family = 'Elf' WHERE UPPER(name) = UPPER('Aiuvarin Translator');
UPDATE CREATURE_TABLE set aon_id = 3631, cr_type = 'Npc', family = 'Elf' WHERE UPPER(name) = UPPER('Forlorn Artist');
UPDATE CREATURE_TABLE set aon_id = 3632, cr_type = 'Npc', family = 'Elf' WHERE UPPER(name) = UPPER('Demonbane Warrior');
UPDATE CREATURE_TABLE set aon_id = 3633, cr_type = 'Npc', family = 'Elf' WHERE UPPER(name) = UPPER('Woodland Scouts');
UPDATE CREATURE_TABLE set aon_id = 3634, cr_type = 'Npc', family = 'Elf' WHERE UPPER(name) = UPPER('Elven Court Guard');
UPDATE CREATURE_TABLE set aon_id = 3635, cr_type = 'Npc', family = 'Gnome' WHERE UPPER(name) = UPPER('Gnome Philomath');
UPDATE CREATURE_TABLE set aon_id = 3636, cr_type = 'Npc', family = 'Gnome' WHERE UPPER(name) = UPPER('Bleachling Survivor');
UPDATE CREATURE_TABLE set aon_id = 3637, cr_type = 'Npc', family = 'Gnome' WHERE UPPER(name) = UPPER('Gnome Daredevil');
UPDATE CREATURE_TABLE set aon_id = 3638, cr_type = 'Npc', family = 'Gnome' WHERE UPPER(name) = UPPER('Razzle Dazzler');
UPDATE CREATURE_TABLE set aon_id = 3639, cr_type = 'Npc', family = 'Gnome' WHERE UPPER(name) = UPPER('Gnome Conservationist');
UPDATE CREATURE_TABLE set aon_id = 3640, cr_type = 'Npc', family = 'Goblin' WHERE UPPER(name) = UPPER('Goblin Chef');
UPDATE CREATURE_TABLE set aon_id = 3641, cr_type = 'Npc', family = 'Goblin' WHERE UPPER(name) = UPPER('Goblin Scavenger');
UPDATE CREATURE_TABLE set aon_id = 3642, cr_type = 'Npc', family = 'Goblin' WHERE UPPER(name) = UPPER('Goblin Get Gang');
UPDATE CREATURE_TABLE set aon_id = 3643, cr_type = 'Npc', family = 'Goblin' WHERE UPPER(name) = UPPER('Big Boss Goblin');
UPDATE CREATURE_TABLE set aon_id = 3644, cr_type = 'Npc', family = 'Halfling' WHERE UPPER(name) = UPPER('Halfling Head Chef');
UPDATE CREATURE_TABLE set aon_id = 3645, cr_type = 'Npc', family = 'Halfling' WHERE UPPER(name) = UPPER('Bill-Band');
UPDATE CREATURE_TABLE set aon_id = 3646, cr_type = 'Npc', family = 'Halfling' WHERE UPPER(name) = UPPER('Halfling Smuggler');
UPDATE CREATURE_TABLE set aon_id = 3647, cr_type = 'Npc', family = 'Halfling' WHERE UPPER(name) = UPPER('Halfling Yarnspinner');
UPDATE CREATURE_TABLE set aon_id = 3648, cr_type = 'Npc', family = 'Hobgoblin' WHERE UPPER(name) = UPPER('Hobgoblin Spellbreaker');
UPDATE CREATURE_TABLE set aon_id = 3649, cr_type = 'Npc', family = 'Hobgoblin' WHERE UPPER(name) = UPPER('Hobgoblin Battalion');
UPDATE CREATURE_TABLE set aon_id = 3650, cr_type = 'Npc', family = 'Hobgoblin' WHERE UPPER(name) = UPPER('Hobgoblin Vanguard');
UPDATE CREATURE_TABLE set aon_id = 3651, cr_type = 'Npc', family = 'Kholo' WHERE UPPER(name) = UPPER('Bone Scavenger');
UPDATE CREATURE_TABLE set aon_id = 3652, cr_type = 'Npc', family = 'Kholo' WHERE UPPER(name) = UPPER('Kholo Pragmatist');
UPDATE CREATURE_TABLE set aon_id = 3653, cr_type = 'Npc', family = 'Kholo' WHERE UPPER(name) = UPPER('Kholo Outrider');
UPDATE CREATURE_TABLE set aon_id = 3654, cr_type = 'Npc', family = 'Kobold' WHERE UPPER(name) = UPPER('Kobold Trapper');
UPDATE CREATURE_TABLE set aon_id = 3655, cr_type = 'Npc', family = 'Kobold' WHERE UPPER(name) = UPPER('Kobold Egg Guardian');
UPDATE CREATURE_TABLE set aon_id = 3656, cr_type = 'Npc', family = 'Leshy' WHERE UPPER(name) = UPPER('Root Leshy Groundskeeper');
UPDATE CREATURE_TABLE set aon_id = 3657, cr_type = 'Npc', family = 'Leshy' WHERE UPPER(name) = UPPER('Tumbleweed Leshy Courier');
UPDATE CREATURE_TABLE set aon_id = 3658, cr_type = 'Npc', family = 'Leshy' WHERE UPPER(name) = UPPER('Corn Leshy Throng');
UPDATE CREATURE_TABLE set aon_id = 3659, cr_type = 'Npc', family = 'Leshy' WHERE UPPER(name) = UPPER('Gourd Leshy Witch');
UPDATE CREATURE_TABLE set aon_id = 3660, cr_type = 'Npc', family = 'Lizardfolk' WHERE UPPER(name) = UPPER('Tidewater Guard');
UPDATE CREATURE_TABLE set aon_id = 3661, cr_type = 'Npc', family = 'Lizardfolk' WHERE UPPER(name) = UPPER('Iruxi Masked Mummer');
UPDATE CREATURE_TABLE set aon_id = 3663, cr_type = 'Npc', family = 'Orc' WHERE UPPER(name) = UPPER('Orc Gamekeeper');
UPDATE CREATURE_TABLE set aon_id = 3664, cr_type = 'Npc', family = 'Orc' WHERE UPPER(name) = UPPER('Dromaar Lorekeeper');
UPDATE CREATURE_TABLE set aon_id = 3665, cr_type = 'Npc', family = 'Orc' WHERE UPPER(name) = UPPER('Orc Skullcrushers');
UPDATE CREATURE_TABLE set aon_id = 3666, cr_type = 'Npc', family = 'Orc' WHERE UPPER(name) = UPPER('Orc Veteran Master');
UPDATE CREATURE_TABLE set aon_id = 3667, cr_type = 'Npc', family = 'Ratfolk' WHERE UPPER(name) = UPPER('Tunnel Viper');
UPDATE CREATURE_TABLE set aon_id = 3668, cr_type = 'Npc', family = 'Ratfolk' WHERE UPPER(name) = UPPER('Swarm Voice');
UPDATE CREATURE_TABLE set aon_id = 3669, cr_type = 'Npc', family = 'Ratfolk' WHERE UPPER(name) = UPPER('Bone Mother');
UPDATE CREATURE_TABLE set aon_id = 3670, cr_type = 'Npc', family = 'Tengu' WHERE UPPER(name) = UPPER('Gambling Companion');
UPDATE CREATURE_TABLE set aon_id = 3671, cr_type = 'Npc', family = 'Tengu' WHERE UPPER(name) = UPPER('Jinx Eater');
UPDATE CREATURE_TABLE set aon_id = 3672, cr_type = 'Npc', family = 'Tengu' WHERE UPPER(name) = UPPER('Tengu Bladesmith');
UPDATE CREATURE_TABLE set aon_id = 3673, cr_type = 'Npc', family = 'Tripkee' WHERE UPPER(name) = UPPER('Tripkee Scout');
UPDATE CREATURE_TABLE set aon_id = 3674, cr_type = 'Npc', family = 'Tripkee' WHERE UPPER(name) = UPPER('Tripkee Camoufleur');
UPDATE CREATURE_TABLE set aon_id = 3680, cr_type = 'Npc', family = 'Kobold' WHERE UPPER(name) = UPPER('Kobold Earth Diver');
UPDATE CREATURE_TABLE set aon_id = 3686, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Besieged Logging Crew');
UPDATE CREATURE_TABLE set aon_id = 3687, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Sigrid Jandevik');
UPDATE CREATURE_TABLE set aon_id = 3701, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Izurran');
UPDATE CREATURE_TABLE set aon_id = 3703, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Sylvarindarian');
UPDATE CREATURE_TABLE set aon_id = 3704, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Shadebound Pixie Guard');
UPDATE CREATURE_TABLE set aon_id = 3705, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Shadow Sage');
UPDATE CREATURE_TABLE set aon_id = 1540, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Ekujae Guardian');
UPDATE CREATURE_TABLE set aon_id = 2161, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Foolish Hunter');
UPDATE CREATURE_TABLE set aon_id = 3417, cr_type = 'Npc', family = 'Courtier' WHERE UPPER(name) = UPPER('Courtesan');
UPDATE CREATURE_TABLE set aon_id = 3467, cr_type = 'Npc', family = 'Explorer' WHERE UPPER(name) = UPPER('Forager');
UPDATE CREATURE_TABLE set aon_id = 3477, cr_type = 'Npc', family = 'Explorer' WHERE UPPER(name) = UPPER('Woolly Wrangler');
UPDATE CREATURE_TABLE set aon_id = 3675, cr_type = 'Npc', family = 'Tripkee' WHERE UPPER(name) = UPPER('Tripkee Fiend-Keeper');
UPDATE CREATURE_TABLE set aon_id = 3688, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Hateful Logger');









UPDATE CREATURE_TABLE set aon_id = 893, cr_type = 'Npc', family = 'Devotees' WHERE UPPER(name) = UPPER('Acolyte of Nethys');
UPDATE CREATURE_TABLE set aon_id = 893, cr_type = 'Npc', family = 'Devotees' WHERE UPPER(name) = UPPER('Acolyte of Pharasma');
UPDATE CREATURE_TABLE set aon_id = 896, cr_type = 'Npc', family = 'Devotees' WHERE UPPER(name) = UPPER('Priest of Pharasma');
UPDATE CREATURE_TABLE set aon_id = 896, cr_type = 'Npc', family = 'Devotees' WHERE UPPER(name) = UPPER('Priest Of Kabriri');
UPDATE CREATURE_TABLE set aon_id = 896, cr_type = 'Npc', family = 'Devotees' WHERE UPPER(name) = UPPER('Priest of Blackfingers');
UPDATE CREATURE_TABLE set aon_id = 1030, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Morlibint');
UPDATE CREATURE_TABLE set aon_id = 1034, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Eleukas');
UPDATE CREATURE_TABLE set aon_id = 1042, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Lisavet');
UPDATE CREATURE_TABLE set aon_id = 1053, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Chea');
UPDATE CREATURE_TABLE set aon_id = 1444, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Wendlyn');
UPDATE CREATURE_TABLE set aon_id = 1445, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Tino Tung (Level 9)');
UPDATE CREATURE_TABLE set aon_id = 1445, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Tino Tung (Level 13)');
UPDATE CREATURE_TABLE set aon_id = 1445, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Tino (Oni Form)');
UPDATE CREATURE_TABLE set aon_id = 1475, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Shino Hakusa (Level 14)');
UPDATE CREATURE_TABLE set aon_id = 1475, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Shino Hakusa (Level 16)');
UPDATE CREATURE_TABLE set aon_id = 1475, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Shino Hakusa (Level 20)');
UPDATE CREATURE_TABLE set aon_id = 1477, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Gristleburst');
UPDATE CREATURE_TABLE set aon_id = 1565, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Corrupt Guard');
UPDATE CREATURE_TABLE set aon_id = 1638, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Fire-pot Ubanu');
UPDATE CREATURE_TABLE set aon_id = 1640, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Salathiss');
UPDATE CREATURE_TABLE set aon_id = 1692, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Ajbal Kimon');
-- UPDATE CREATURE_TABLE set aon_id = 1750, cr_type = 'Npc', family = 'Threshold of Knowledge Pregenerated Characters' WHERE UPPER(name) = UPPER('');Ekene,
-- UPDATE CREATURE_TABLE set aon_id = 1751, cr_type = 'Npc', family = 'Threshold of Knowledge Pregenerated Characters' WHERE UPPER(name) = UPPER('');Kalaggi Nakutu,
-- UPDATE CREATURE_TABLE set aon_id = 1752, cr_type = 'Npc', family = 'Threshold of Knowledge Pregenerated Characters' WHERE UPPER(name) = UPPER('');Muruwa,
-- UPDATE CREATURE_TABLE set aon_id = 1753, cr_type = 'Npc', family = 'Threshold of Knowledge Pregenerated Characters' WHERE UPPER(name) = UPPER('');Ufi,
-- UPDATE CREATURE_TABLE set aon_id = 1754, cr_type = 'Npc', family = 'Threshold of Knowledge Pregenerated Characters' WHERE UPPER(name) = UPPER('');Zane Ikundi,
UPDATE CREATURE_TABLE set aon_id = 1761, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Burning Mammoth Hunter');
UPDATE CREATURE_TABLE set aon_id = 1765, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER("Ardissa's Porter");
UPDATE CREATURE_TABLE set aon_id = 1769, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Pakano (Level 12)');
UPDATE CREATURE_TABLE set aon_id = 1821, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Rhino Warriors');
UPDATE CREATURE_TABLE set aon_id = 1940, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Glaz Nixbrix');
UPDATE CREATURE_TABLE set aon_id = 1941, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Shoma Lyzerius');
UPDATE CREATURE_TABLE set aon_id = 1978, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Sabora Sharkosa');
UPDATE CREATURE_TABLE set aon_id = 1986, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Corrupt Shieldmarshal (Clan Pistol)');
UPDATE CREATURE_TABLE set aon_id = 1986, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Corrupt Shieldmarshal (Jezail)');
UPDATE CREATURE_TABLE set aon_id = 2024, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Andera Paldreen');
UPDATE CREATURE_TABLE set aon_id = 2043, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Bone Shard Tough');
UPDATE CREATURE_TABLE set aon_id = 2049, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Kepgeda the Hag-Nailed');
UPDATE CREATURE_TABLE set aon_id = 2082, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Grace "The Rhino" Owano');
UPDATE CREATURE_TABLE set aon_id = 2101, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Tanessa Fleer');
-- UPDATE CREATURE_TABLE set aon_id = 2388, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('');Amiri (Level 1)
-- UPDATE CREATURE_TABLE set aon_id = 2389, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('');Amiri (Level 11)
-- UPDATE CREATURE_TABLE set aon_id = 2390, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('');Ekundayo (Level 1)
-- UPDATE CREATURE_TABLE set aon_id = 2391, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('');Ekundayo (Level 6)
-- UPDATE CREATURE_TABLE set aon_id = 2393, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('');Jubilost Narthropple (Level 1)
-- UPDATE CREATURE_TABLE set aon_id = 2395, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('');Linzi (Level 1)
-- UPDATE CREATURE_TABLE set aon_id = 2397, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('');Nok-Nok (Level 1)
-- UPDATE CREATURE_TABLE set aon_id = 2399, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('');Tristian (Level 1)
-- UPDATE CREATURE_TABLE set aon_id = 2401, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('');Valerie (Level 1)
-- UPDATE CREATURE_TABLE set aon_id = 2437, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('');Dead Fane
UPDATE CREATURE_TABLE set aon_id = 2467, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Sakuachi');
UPDATE CREATURE_TABLE set aon_id = 2515, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Etward Ritalson');
UPDATE CREATURE_TABLE set aon_id = 2555, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Arodeth');
UPDATE CREATURE_TABLE set aon_id = 2574, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('The Prince of Wolves');
UPDATE CREATURE_TABLE set aon_id = 2735, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Hu Ban-Niang');
UPDATE CREATURE_TABLE set aon_id = 2736, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Shou Matsuki');
UPDATE CREATURE_TABLE set aon_id = 3099, cr_type = 'Npc', family = 'Minotaur' WHERE UPPER(name) = UPPER('Minotaur Hunter (BB)');
UPDATE CREATURE_TABLE set aon_id = 3099, cr_type = 'Npc', family = 'Minotaur' WHERE UPPER(name) = UPPER('Minotaur Hunter');
UPDATE CREATURE_TABLE set aon_id = 3139, cr_type = 'Npc', family = 'Planar Scion' WHERE UPPER(name) = UPPER('Duskwalker Ghost Hunter');
UPDATE CREATURE_TABLE set aon_id = 3369, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Red Bishop');
UPDATE CREATURE_TABLE set aon_id = 3399, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Saviya');
UPDATE CREATURE_TABLE set aon_id = 3536, cr_type = 'Npc', family = 'Mystic' WHERE UPPER(name) = UPPER('Enigmatic Conspirant');
UPDATE CREATURE_TABLE set aon_id = 3662, cr_type = 'Npc', family = 'Orc' WHERE UPPER(name) = UPPER('Orc Agriculturist');
UPDATE CREATURE_TABLE set aon_id = 3699, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Alyce Quinley');
UPDATE CREATURE_TABLE set aon_id = 3700, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Emorga All-Seer');





































UPDATE CREATURE_TABLE set aon_id = 895, cr_type = 'Npc', family = 'Devotees' WHERE UPPER(name) = UPPER('Zealot of Asmodeus');
UPDATE CREATURE_TABLE set aon_id = 1028, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Duhgik');
UPDATE CREATURE_TABLE set aon_id = 1029, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER("Pr'rall");
UPDATE CREATURE_TABLE set aon_id = 1052, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Urok');
UPDATE CREATURE_TABLE set aon_id = 1391, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Zhang Yong');
UPDATE CREATURE_TABLE set aon_id = 1473, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Syu Tak-nwa (Level 14)');
UPDATE CREATURE_TABLE set aon_id = 1473, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Syu Tak-nwa (Level 16)');
UPDATE CREATURE_TABLE set aon_id = 1473, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Syu Tak-nwa (Level 20)');
UPDATE CREATURE_TABLE set aon_id = 1474, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Blue Viper (Level 20)');
UPDATE CREATURE_TABLE set aon_id = 1474, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Blue Viper (Level 16)');
UPDATE CREATURE_TABLE set aon_id = 1474, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Blue Viper (Level 14)');
UPDATE CREATURE_TABLE set aon_id = 1476, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Ran-to (Level 20)');
UPDATE CREATURE_TABLE set aon_id = 1476, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Ran-to (Level 16)');
UPDATE CREATURE_TABLE set aon_id = 1476, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Ran-to (Level 14)');
UPDATE CREATURE_TABLE set aon_id = 1480, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Sixth Pillar Student');
UPDATE CREATURE_TABLE set aon_id = 1487, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Arms of Balance (Jivati Rovat)');
UPDATE CREATURE_TABLE set aon_id = 1487, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Arms of Balance (Pravan Majinapti)');
UPDATE CREATURE_TABLE set aon_id = 1487, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Arms of Balance (Ranya Shibhatesh)');
UPDATE CREATURE_TABLE set aon_id = 1487, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Arms of Balance (Usvani)');
UPDATE CREATURE_TABLE set aon_id = 1488, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Yarrika Mulandez');
-- UPDATE CREATURE_TABLE set aon_id = 1499, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('None');Phuthi, []
UPDATE CREATURE_TABLE set aon_id = 1524, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Yabin (White Serpent Form)');
UPDATE CREATURE_TABLE set aon_id = 1578, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Bshez "Sand Claws" Shak');
UPDATE CREATURE_TABLE set aon_id = 1591, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Ingnovim Tluss');
UPDATE CREATURE_TABLE set aon_id = 1592, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER("Ingnovim's Assistant");
UPDATE CREATURE_TABLE set aon_id = 1620, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Yoh Souran');
UPDATE CREATURE_TABLE set aon_id = 1639, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Froglegs');
UPDATE CREATURE_TABLE set aon_id = 1694, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Thiarvo the Quick');
UPDATE CREATURE_TABLE set aon_id = 1710, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Worknesh');
UPDATE CREATURE_TABLE set aon_id = 1712, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Iobane Magus');
UPDATE CREATURE_TABLE set aon_id = 1832, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Ivarsa');
UPDATE CREATURE_TABLE set aon_id = 1833, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Metuak');
UPDATE CREATURE_TABLE set aon_id = 1835, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Unshadowed Koride');
UPDATE CREATURE_TABLE set aon_id = 1977, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Ambrost Mugland');
UPDATE CREATURE_TABLE set aon_id = 1992, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Anjelique Loveless');
UPDATE CREATURE_TABLE set aon_id = 1993, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Ibrium');
UPDATE CREATURE_TABLE set aon_id = 1994, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Parsus');
-- UPDATE CREATURE_TABLE set aon_id = 1996, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('None');Jaleen
-- UPDATE CREATURE_TABLE set aon_id = 1997, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('None');Rhovo
UPDATE CREATURE_TABLE set aon_id = 2099, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Lasheeli');
-- UPDATE CREATURE_TABLE set aon_id = 2394, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('None');Jubilost Narthropple (Level 8)
-- UPDATE CREATURE_TABLE set aon_id = 2396, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('None');Linzi (Level 7)
-- UPDATE CREATURE_TABLE set aon_id = 2398, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('None');Nok-Nok (Level 5)
-- UPDATE CREATURE_TABLE set aon_id = 2400, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('None');Tristian (Level 10), []
-- UPDATE CREATURE_TABLE set aon_id = 2402, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('None');Valerie (Level 9)
UPDATE CREATURE_TABLE set aon_id = 2436, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER("Kemnebi's Puppet");
UPDATE CREATURE_TABLE set aon_id = 2556, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Drustan');
UPDATE CREATURE_TABLE set aon_id = 2594, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Raven Nicoletta');
UPDATE CREATURE_TABLE set aon_id = 2595, cr_type = 'Npc', family = NULL WHERE UPPER(name) = UPPER('Zellara Esmeranda');

